#!/usr/bin/env python3
"""Generate ``data/README.md`` -- the map of every tracked file under data/.

The old ``data/lit/README.md`` documented one file that did not exist, omitted five that
did, and called a run ledger "curated". A hand-written map drifts; this one cannot:

* every file ``git ls-files data`` reports must be covered by an entry in
  ``DESCRIPTIONS`` (its own path, or its directory) -- an undescribed file fails the build;
* every described path must exist -- a ghost fails the build;
* ``tests/unit/test_data_readme.py`` runs ``--check`` so a stale README fails CI.

Descriptions are the hand-curated part and live here. Keep them to one line and say what
the file IS and who reads it, not where it is.

Run inside Docker:
    python scripts/generators/build_data_readme.py           # write data/README.md
    python scripts/generators/build_data_readme.py --check   # exit 1 if stale
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Optional

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src import data_paths  # noqa: E402

# path (file or directory, relative to repo root) -> one-line description.
# A directory entry covers every file beneath it that has no entry of its own.
DESCRIPTIONS: Dict[str, str] = {
    "data/formulation_grid.yml": "Built-in candidate formulation grid for inverse-design runs (`src/pipeline.py`).",
    "data/interventions.yml": "Intervention library: per-unit barrier deltas used by the Bayesian optimiser.",
    # ---- keys
    "data/keys": "The join layer (Phase 3). Generated files; edit the seeds in the generators, not the YAML.",
    "data/keys/compounds.yml": "One row per compound identity (InChIKey for molecules) with every spelling seen in the repo; `src/compound_keys.py` resolves names through it. Generated by `scripts/generators/build_compound_registry.py`.",
    "data/keys/papers.yml": "One row per DOI cited anywhere under data/ or the kinetic core, with every citing record; `src/paper_keys.py`. Generated by `scripts/generators/build_paper_registry.py`; `autogenerated_unverified`.",
    # ---- schemas
    "data/schemas": "JSON Schemas enforced by `scripts/ci/schema_gate.py`.",
    "data/schemas/benchmark.schema.json": "Schema every benchmark payload validates against (core fields, closed enums, measured XOR reference volatiles).",
    # ---- species
    "data/species": "Compound and precursor definitions (SMILES, CAS, InChI, odour thresholds). The source of chemical identity for `compounds.yml`.",
    "data/species/desirable_targets.yml": "20 meat-relevant target odorants with odour thresholds; read by `sensory`, `experiment_value`, `recommend`.",
    "data/species/off_flavour_targets.yml": "6 off-note compounds (beany/green/fatty) with thresholds; same readers.",
    "data/species/toxic_markers.yml": "8 safety markers (AGEs, acrylamide, HCAs) with IARC class.",
    "data/species/sensory_tags.yml": "Tag -> compound display-name lists used by the pipeline's target/minimise tags.",
    "data/species/precursors.yml": "Precursors by category (amino acids, sugars, exogenous, intermediates, lipids); `src/precursor_resolver.py`.",
    # ---- lit
    "data/lit": "Literature-derived constants, priors, reference payloads and the intake registries. See the per-file lines below and `data/lit/README.md` for the ingestion workflow.",
    "data/lit/README.md": "How to register a paper and run the literature learning loop.",
    "data/lit/arrhenius_params.yml": "Pre-exponential factors and activation energies per reaction family (Cantera export lane); its header records a known kJ/kcal collision with `FAST_BARRIERS`.",
    "data/lit/henry_constants.yml": "Air-water partition coefficients and solution enthalpies for 31 volatiles; `src/headspace.py`.",
    "data/lit/binding_constants.yml": "Measured protein-flavour binding constants with verbatim source quotes and verification status; `src/protein_binding.py`. The record shape the rest of this directory should converge on.",
    "data/lit/lipid_oxidation_calibration.json": "Lipid-oxidation kinetics, branching ratios and per-matrix lipid profiles; `src/lipid_oxidation.py`.",
    "data/lit/computational_priors.json": "22 prior tables in one file (accessibility windows, class profiles, per-family priors, DFT-era kinetic priors); read by 10 modules. Split planned (Phase 4).",
    "data/lit/flavor_reference_payloads.json": "59 odour-threshold / concentration anchors for character-impact compounds, by chemistry section.",
    "data/lit/safety_reference_payloads.json": "43 regulatory and industrial reference limits for undesirable compounds; `src/safety.py`.",
    "data/lit/extrusion_damage_reference_payloads.json": "4 damage-marker reference ranges (furosine, CML, CEL, LAL); `src/extrusion.py`. Merge into safety payloads planned.",
    "data/lit/retention_reference_payloads.json": "Volatile retention/release records per protein, incl. withdrawn (`unsourced_withdrawn`) rows; `src/headspace.py`, `literature_runtime`.",
    "data/lit/process_state_calibrations.json": "26 extrusion / heat / shear calibration records (accessibility scaling); `src/extrusion.py`, `matrix_correction`.",
    "data/lit/matrix_decision_panel.json": "Compound -> target class + evidence state truth table with aliases; seed of `compounds.yml`; `src/matrix_targets.py`.",
    "data/lit/matrix_family_coverage_registry.json": "The 8 canonical matrix families and what each supports; the intended closed vocabulary for `matrix_family`.",
    "data/lit/chemistry_family_scope_registry.json": "The 16 chemistry lanes as product scope (status, priority, next action).",
    "data/lit/family_ingestion_plan.json": "The same 16 lanes as an ingestion roadmap (waves, payload types, target modules). Merge with the scope registry planned.",
    "data/lit/process_gap_registry.json": "5 structural gaps literature cannot close; overlaps `benchmark_intake_registry.structural_gaps`.",
    "data/lit/benchmark_intake_registry.json": "The paper catalogue: 205 references scored against the C1-C8 intake criteria, with repair ledgers. `paper_id` of choice for `papers.yml`.",
    "data/lit/refinement_surrogate_patches.json": "RETIRED barrier-offset tombstone; `accepted_offsets` must stay empty (guarded by a test).",
    "data/lit/extraction_dossiers": "Per-paper extraction records (verbatim quotes, digitised tables, unit reconciliations) cited as provenance strings by `src/kinetic_core/`. `k*_` and `research_round*` files are cross-paper syntheses.",
    "data/lit/timeseries": "Digitised concentration-vs-time trajectories (Martins 2003/2005, Brands 2002) used by the trunk-rate fit; declared fit targets are gated by `scripts/ci/fit_target_gate.py`.",
    # ---- benchmarks
    "data/benchmarks": "Observations the model is scored against. Panel discovery is NON-recursive: only the top level is calibration evidence.",
    "data/benchmarks/maillard_validation_benchmarks.md": "Retired evidence record whose sections 1.3/3.1/3.2 are self-declared reconstructed; kept at this path because ~35 provenance notes cite it.",
    "data/benchmarks/external_validation": "Matrix-lane hold-out bundles (`evidence_class: external_validation_only`). Frozen evidence: the generator is write-once (`src/external_validation.py`).",
    "data/benchmarks/external_validation/intake": "The intake YAML each matrix hold-out bundle was materialised from; frozen alongside it.",
    "data/benchmarks/external_validation/maillard_path": "Free-precursor hold-out bundles: the network's out-of-sample test, hand-authored, scored on `holdout_targets`.",
    "data/benchmarks/quarantined": "Benchmarks retired for unverifiable sources; kept for forensics, never scored.",
    "data/benchmarks/step_level_unreachable": "Verified rows the network cannot execute (see README there); kept off the panel by design.",
    # ---- protocols
    "data/protocols": "Wet-lab contracts and intake specifications.",
    "data/protocols/matrix_experiment_intake_schema.json": "Required-field lists for intake YAML (`src/matrix_experiment_intake.py`); to become a JSON Schema under data/schemas.",
    "data/protocols/example_matrix_experiment_intake.yaml": "Canonical intake example used by `maillard ingest` and its tests.",
    "data/protocols/ppi_spi_primary_benchmark_contract.json": "The PPI/SPI primary benchmark package contract (DOE generator, campaign).",
    "data/protocols/extrusion_external_closure_contract.json": "Extrusion external-closure package contract.",
    "data/protocols/dha_lysinoalanine_external_package_contract.json": "DHA / lysinoalanine external package contract.",
    "data/protocols/pea_soy_mixed_external_package_contract.json": "Pea/soy mixed-matrix external package contract.",
    "data/protocols/pea_iso_protocol_pilot_intake.yaml": "Protocol-pilot intake for pea isolate (hand-written comparison contract; `conc_ppb` refreshed from the model by the reproducibility snapshot generator).",
    "data/protocols/soy_iso_protocol_pilot_intake.yaml": "Protocol-pilot intake for soy isolate; same status.",
    # ---- research corpus
    "data/research_corpus": "LLM research dumps and literature syntheses (renamed from Gemini_Deep_Research on 2026-09-02). NOT provenance: kept so `scripts/ci/citation_gate.py` can detect laundered citations, and mined by `deep_research_tracker.py`.",
    "data/research_corpus/raw": "The raw deep-research dumps, unedited.",
}

SKIP_BASENAMES = {".DS_Store"}


def tracked_files() -> List[Path]:
    out = subprocess.run(["git", "ls-files", "data"], cwd=ROOT, capture_output=True, text=True, check=True).stdout
    return [Path(line) for line in out.splitlines() if line and Path(line).name not in SKIP_BASENAMES and line != "data/README.md"]


def describe(rel: Path) -> Optional[str]:
    if str(rel) in DESCRIPTIONS:
        return DESCRIPTIONS[str(rel)]
    for parent in rel.parents:
        if str(parent) in DESCRIPTIONS:
            return None  # covered by its directory entry
    return None


def build() -> str:
    files = tracked_files()
    problems: List[str] = []
    for rel in files:
        if str(rel) not in DESCRIPTIONS and not any(str(p) in DESCRIPTIONS for p in rel.parents):
            problems.append(f"undescribed: {rel}")
    for key in DESCRIPTIONS:
        if not (ROOT / key).exists():
            problems.append(f"described but absent: {key}")
    if problems:
        raise SystemExit("data/README.md cannot be built:\n  " + "\n  ".join(problems))

    by_dir: Dict[str, List[Path]] = defaultdict(list)
    for rel in files:
        by_dir[str(rel.parent)].append(rel)

    lines = [
        "# `data/` — curated inputs",
        "",
        "> Generated by `scripts/generators/build_data_readme.py` from `git ls-files data` and a hand-written",
        "> description map in that script. Do not edit this file; edit the map and re-run. A tracked file with no",
        "> description, or a described file that is gone, fails the build (`tests/unit/test_data_readme.py`).",
        "",
        "Three trees, three rules (`src/data_paths.py`): **`data/`** is curated input and read-only at runtime",
        "(`scripts/ci/data_readonly_gate.py`); **`results/`** is generated; **`docs/`** is for humans. Every path in",
        "code comes from `src/data_paths.py`; every load goes through `src/data_access.py` (missing files raise).",
        "Names resolve through `data/keys/` (`src/compound_keys.py`, `src/paper_keys.py`). Benchmarks validate",
        "against `data/schemas/` (`scripts/ci/schema_gate.py`). The restructure record is `tasks/data_restructure_plan.md`.",
        "",
        f"Tracked files: **{len(files)}**. Local-only (gitignored): `data/articles/` (primary-source PDFs, ~160 MB).",
        "",
    ]
    for directory in sorted(by_dir, key=lambda d: (d.count("/"), d)):
        entries = sorted(by_dir[directory])
        heading = directory if directory != "data" else "data (top level)"
        lines.append(f"## `{heading}`")
        lines.append("")
        if directory in DESCRIPTIONS:
            lines.append(DESCRIPTIONS[directory])
            lines.append("")
        described = [(rel, DESCRIPTIONS[str(rel)]) for rel in entries if str(rel) in DESCRIPTIONS]
        grouped = [rel for rel in entries if str(rel) not in DESCRIPTIONS]
        if described:
            lines.append("| file | what it is |")
            lines.append("|---|---|")
            for rel, text in described:
                lines.append(f"| `{rel.name}` | {text} |")
            lines.append("")
        if grouped:
            lines.append(f"{len(grouped)} files covered by the directory description above: " + ", ".join(f"`{r.name}`" for r in grouped[:12]) + (" …" if len(grouped) > 12 else ""))
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    text = build()
    target = data_paths.DATA_ROOT / "README.md"
    if args.check:
        if (target.read_text(encoding="utf-8") if target.exists() else "") != text:
            print(f"{data_paths.rel(target)} is stale; re-run without --check", file=sys.stderr)
            return 1
        print(f"{data_paths.rel(target)} is current")
        return 0
    target.write_text(text, encoding="utf-8")
    print(f"wrote {data_paths.rel(target)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
