#!/usr/bin/env python3
"""Build ``data/keys/papers.yml`` -- the paper key registry.

Why this exists (cleaning branch, Phase 3, 2026-09-01)
-------------------------------------------------------
233 distinct DOIs are cited across the registries, benchmarks, payloads and timeseries
files, and 177 of them appear in more than one file under a different record id each
time (``acs_jafc_3c05991_ppi_spi_partitioning`` / ``jafc_3c05991_ppi_hexanal_binding`` /
``jafc_3c05991_hexanal_binding`` for one paper). Nothing joined them.

This script produces ONE row per DOI:

* ``paper_id``   -- the intake-registry id when the paper has one, else the SLR ledger's
                    ``paper_id``, else the extraction-dossier stem, else a slug of the DOI;
* ``doi``        -- normalised (lower-case, no resolver prefix, no trailing punctuation);
* ``citation``   -- the first citation string seen (intake registry preferred);
* ``dossier``    -- ``data/lit/extraction_dossiers/<file>`` whose identity table prints this DOI;
* ``record_ids`` -- every record id that cites the DOI, grouped by file, so a reader can
                    find all the places one paper is used.

Everything here is DERIVED from the existing files and labelled
``verification_status: autogenerated_unverified``. It does not assert that a DOI is
correct (scripts/ci/citation_gate.py does that); it asserts which records share one.
Local PDFs under data/articles/ are deliberately not matched here, so the output is the
same on a machine that does not have them.

Run:
    python scripts/generators/build_paper_registry.py            # write data/keys/papers.yml
    python scripts/generators/build_paper_registry.py --check    # exit 1 if stale
"""
from __future__ import annotations

import argparse
import glob
import json
import re
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Set

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import yaml  # noqa: E402

from src import data_access, data_paths, paper_keys  # noqa: E402

DOI_FIELDS = {"doi", "source_doi", "doi_new", "resolved_doi", "primary_doi"}
ID_FIELDS = ("id", "paper_id", "benchmark_id", "artifact_id", "registry_id", "reference_id", "evidence_id", "record_id", "source_id")
normalise_doi = paper_keys.normalise_doi

# --- which dossier is a paper's dossier -------------------------------------------------
#
# A dossier declares the paper it is FOR in its identity block: a markdown table row whose
# first cell is labelled DOI, or -- for the handful of dossiers with no identity table -- a
# "DOI ..." line in the header preamble, above the first section heading or rule.
#
# The label is spelled a dozen ways across the 290 files (``DOI``, ``**DOI**``, ``DOI / PII``,
# ``DOI / article ID``, ``DOI as printed``, ``★ **DOI**``) and the value is usually wrapped in
# a code span and bold. Until 2026-09-11 only the bare ``| DOI |`` spelling was read, which
# left 89 dossiers unlinked.
#
# Only the FIRST labelled line counts, and it counts even when it carries no DOI: a dossier
# whose identity row says "NO DOI IS PRINTED IN THE PDF" has none, and every DOI further down
# such a file belongs to another paper. Widening instead to "the DOI appears anywhere in the
# dossier text" would mis-assign 37 papers -- zhang2024b_extraction.md names a competitor's
# DOI (10.1021/acs.jafc.4c05736) in its opening paragraph while its own identity row reads
# 10.1016/j.foodres.2024.114149, blank1996_extraction.md quotes the DOI of Blank 1997 whose
# own dossier is blank1997_extraction.md, and the k*_synthesis / research_round* files cite
# dozens of DOIs each without being the dossier for any of them.
DOSSIER_DOI_LABEL = re.compile(r"^[\s>*_`\u2605\u2606\u2714\u2705\u26a0\ufe0f]*doi\b", re.I)
DOSSIER_NO_DOI = re.compile(r"^[\s*_`]*no\s+doi\b", re.I)
DOSSIER_HEADER_END = re.compile(r"^(?:-{3,}\s*$|#{2,6}\s)")


def dossier_identity_doi(text: str) -> Optional[str]:
    """The DOI a dossier declares as its own subject, or ``None``."""
    in_header = True
    for line in text.splitlines():
        stripped = line.strip()
        if in_header and DOSSIER_HEADER_END.match(stripped):
            in_header = False
        if stripped.startswith("|"):
            cells = stripped.split("|")
            if len(cells) < 3:
                continue
            cell = cells[1].strip()
            if DOSSIER_NO_DOI.match(cell):
                return None
            if DOSSIER_DOI_LABEL.match(cell):
                return normalise_doi(stripped)
        elif in_header and DOSSIER_DOI_LABEL.match(stripped):
            return normalise_doi(stripped)
    return None


# --- DOIs cited from source code --------------------------------------------------------
#
# The kinetic-core modules carry their provenance in comments and long string literals, both
# of which the source formatter wraps -- inside an implicitly concatenated literal
#
#     "CITE IT. Yu, Seow, Ong & Zhou 2018 (Food Chem. 268:2, 10.1016/j.foodchem."
#     "2018.06.108; yu2018_extraction.md Table 1, step 5) measure the same "
#
# and across a continued comment
#
#     # `data/articles/Kocadagli2016.pdf` (LONGER stem) = Food Chem 10.1016/j.foodchem
#     #                                  .2016.05.150 = glucose/wheat flour = NOT this
#
# Reading physical lines cut the DOI at the wrap, and the leftover trailing "." was then
# trimmed as punctuation, so the fragments "10.1016/j.foodchem" and "10.1021/acs.jafc"
# entered the registry as papers of their own while the real DOIs went unrecorded. Rejoin
# across the wrap first. A fragment is a wrap, not a whole DOI, only when it ends the line
# on a "." or a "/" or the next line resumes with a "."; a complete DOI that merely happens
# to end a line is left alone.
_WRAP_TAIL = re.compile(r"(10\.\d{4,9}/[^\s\"'`|\]]*)[\"']?\s*$")
_WRAP_HEAD = re.compile(r"^[\s#*]*[\"']?([^\s\"'`|\]]+)")


def code_doi_lines(lines: List[str]) -> List[str]:
    """``lines`` with any DOI split across a source wrap rejoined onto its opening line."""
    out = []
    for i, line in enumerate(lines):
        tail = _WRAP_TAIL.search(line)
        if tail and i + 1 < len(lines):
            head = _WRAP_HEAD.match(lines[i + 1])
            cont = head.group(1) if head else ""
            if cont and (tail.group(1).endswith((".", "/")) or cont.startswith(".")):
                line = line[: tail.end(1)] + cont
        out.append(line)
    return out


def _records(payload: Any, rel: str, out: Dict[str, Dict[str, Set[str]]], citations: Dict[str, List[str]]) -> None:
    """Walk a payload; every dict with a DOI field contributes (doi -> file -> record id)."""
    if isinstance(payload, dict):
        dois = set()
        for k, v in payload.items():
            if isinstance(v, str) and k.lower() in DOI_FIELDS:
                d = normalise_doi(v)
                if d:
                    dois.add(d)
        if dois:
            ident = next((str(payload[k]) for k in ID_FIELDS if isinstance(payload.get(k), str) and payload[k].strip()), None)
            cite = payload.get("citation") or payload.get("source_citation") or payload.get("reference")
            for d in dois:
                out.setdefault(d, {}).setdefault(rel, set()).add(ident or "<record without id>")
                if isinstance(cite, str) and cite.strip():
                    citations.setdefault(d, []).append(cite.strip())
        for v in payload.values():
            _records(v, rel, out, citations)
    elif isinstance(payload, list):
        for v in payload:
            _records(v, rel, out, citations)


def gather() -> Dict[str, Any]:
    files: List[Path] = []
    files += [Path(p) for p in sorted(glob.glob(str(data_paths.LIT_DIR / "*.json")))]
    files += [Path(p) for p in sorted(glob.glob(str(data_paths.LIT_DIR / "*.yml")))]
    files += [Path(p) for p in sorted(glob.glob(str(data_paths.LITERATURE_LEDGERS_DIR / "*.json")))]
    files += [Path(p) for p in sorted(glob.glob(str(data_paths.TIMESERIES_DIR / "*.yml")))]
    files += [Path(p) for p in sorted(glob.glob(str(data_paths.BENCHMARKS_DIR / "**" / "*.json"), recursive=True))]
    files += [Path(p) for p in sorted(glob.glob(str(data_paths.SPECIES_DIR / "*.yml")))]
    files += [Path(p) for p in sorted(glob.glob(str(data_paths.PROTOCOLS_DIR / "**" / "*.json"), recursive=True))]
    files += [Path(p) for p in sorted(glob.glob(str(data_paths.PROTOCOLS_DIR / "**" / "*.yaml"), recursive=True))]
    files = [f for f in files if f != data_paths.PAPER_REGISTRY and f != data_paths.COMPOUND_REGISTRY]

    by_doi: Dict[str, Dict[str, Set[str]]] = {}
    citations: Dict[str, List[str]] = {}
    for f in files:
        payload = data_access.load_mapping(f) if f.suffix in {".json", ".yml", ".yaml"} else None
        if payload is None:
            continue
        _records(payload, data_paths.rel(f), by_doi, citations)

    # dossier identity tables
    dossier_by_doi: Dict[str, str] = {}
    dossiers_by_doi: Dict[str, List[str]] = {}
    dossiers_without_doi: List[str] = []
    for f in sorted(glob.glob(str(data_paths.EXTRACTION_DOSSIERS_DIR / "*.md"))):
        text = Path(f).read_text(encoding="utf-8", errors="replace")
        found = dossier_identity_doi(text)
        if found:
            # Several papers have more than one dossier (a re-read, or the same paper filed
            # under two years). First by filename wins, deterministically; the rest are
            # reported in dossiers_sharing_a_doi rather than dropped silently.
            dossiers_by_doi.setdefault(found, []).append(data_paths.rel(f))
            dossier_by_doi.setdefault(found, data_paths.rel(f))
        else:
            dossiers_without_doi.append(data_paths.rel(f))

    # Papers that reach the model only through code: the kinetic-core parameter modules
    # cite DOIs in their provenance strings (the extraction dossiers
    # are their evidence layer). Record them as "<file>:L<line>" so the registry is the
    # union of everything cited, not only the JSON/YAML registries.
    # (src/barrier_constants.py was in this list until retirement step B5b, 2026-09-03.)
    code_files = sorted(glob.glob(str(data_paths.REPO_ROOT / "src" / "kinetic_core" / "*.py")))
    for f in code_files:
        lines = Path(f).read_text(encoding="utf-8", errors="replace").splitlines()
        for lineno, line in enumerate(code_doi_lines(lines), 1):
            for m in paper_keys.DOI_RE.finditer(line):
                d = normalise_doi(m.group(0))
                if d:
                    by_doi.setdefault(d, {}).setdefault(data_paths.rel(f), set()).add(f"L{lineno}")
    # Dossier-only papers (documented, but cited nowhere else yet).
    for d, dossier in dossier_by_doi.items():
        if d not in by_doi:
            by_doi[d] = {dossier: {Path(dossier).stem}}

    intake = data_access.load_json(data_paths.BENCHMARK_INTAKE_REGISTRY)
    intake_by_doi: Dict[str, List[Dict[str, Any]]] = {}
    for ref in intake.get("eligible_references", []):
        d = normalise_doi(ref.get("doi", "") or "")
        if d:
            intake_by_doi.setdefault(d, []).append(ref)
    slr = data_access.load_json(data_paths.SLR_INCORPORATION_MATRIX)
    slr_by_doi: Dict[str, List[Dict[str, Any]]] = {}
    for row in slr.get("entries", []):
        d = normalise_doi(row.get("doi", "") or "")
        if d:
            slr_by_doi.setdefault(d, []).append(row)

    papers = []
    used_ids: Dict[str, str] = {}
    for doi in sorted(by_doi):
        intake_refs = intake_by_doi.get(doi, [])
        slr_rows = slr_by_doi.get(doi, [])
        if intake_refs:
            paper_id, id_source = sorted(r["id"] for r in intake_refs)[0], "benchmark_intake_registry.id"
        elif slr_rows:
            paper_id, id_source = sorted(r["paper_id"] for r in slr_rows)[0], "slr_incorporation_matrix.paper_id"
        elif doi in dossier_by_doi:
            stem = Path(dossier_by_doi[doi]).stem
            paper_id, id_source = re.sub(r"_(extraction|reconciliation)$", "", stem).lower(), "extraction_dossier stem"
        else:
            paper_id, id_source = "doi_" + re.sub(r"[^a-z0-9]+", "_", doi).strip("_"), "doi slug (no registry id anywhere)"
        if paper_id in used_ids:
            # Two DOIs claiming one id: keep the id unique by suffixing the DOI slug.
            paper_id = f"{paper_id}__{re.sub(r'[^a-z0-9]+', '_', doi.split('/', 1)[1])}"
        used_ids[paper_id] = doi
        cites = citations.get(doi, [])
        citation = next((r.get("citation") for r in intake_refs if r.get("citation")), None) or (
            next((r.get("citation") for r in slr_rows if r.get("citation")), None)
        ) or (cites[0] if cites else None)
        papers.append(
            {
                "paper_id": paper_id,
                "paper_id_source": id_source,
                "doi": doi,
                "citation": citation,
                "dossier": dossier_by_doi.get(doi),
                "intake_ids": sorted({r["id"] for r in intake_refs}),
                "slr_paper_ids": sorted({r["paper_id"] for r in slr_rows}),
                "record_ids": {f: sorted(ids) for f, ids in sorted(by_doi[doi].items())},
                "verification_status": "autogenerated_unverified",
            }
        )
    return {
        "schema_version": 1,
        "generated_by": "scripts/generators/build_paper_registry.py",
        "note": (
            "One row per DOI cited anywhere under data/. paper_id is the intake-registry id "
            "where one exists (else the SLR ledger id, else the dossier stem, else a DOI slug). "
            "record_ids lists every record that cites the DOI, by file. Derived, not curated: "
            "this file asserts which records share a paper, not that the DOI is right "
            "(scripts/ci/citation_gate.py does that). Do not hand-edit: re-run the generator."
        ),
        "counts": {
            "papers": len(papers),
            "with_dossier": sum(1 for p in papers if p["dossier"]),
            "with_intake_id": sum(1 for p in papers if p["intake_ids"]),
            "cited_in_more_than_one_file": sum(1 for p in papers if len(p["record_ids"]) > 1),
            "cited_only_from_code_or_dossier": sum(
                1 for p in papers if all(f.startswith(("src/", "data/lit/extraction_dossiers/")) for f in p["record_ids"])
            ),
        },
        "dossiers_without_printed_doi": dossiers_without_doi,
        "dossiers_sharing_a_doi": {d: fs for d, fs in sorted(dossiers_by_doi.items()) if len(fs) > 1},
        "papers": papers,
    }


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    payload = gather()
    text = yaml.safe_dump(payload, sort_keys=False, allow_unicode=True, width=110)
    target = data_paths.PAPER_REGISTRY
    if args.check:
        current = target.read_text(encoding="utf-8") if target.exists() else ""
        if current != text:
            print(f"{data_paths.rel(target)} is stale; re-run without --check", file=sys.stderr)
            return 1
        print(f"{data_paths.rel(target)} is current ({payload['counts']['papers']} papers)")
        return 0
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text, encoding="utf-8")
    print(f"wrote {data_paths.rel(target)}: {json.dumps(payload['counts'])}; dossiers without a printed DOI: {len(payload['dossiers_without_printed_doi'])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
