"""
Build Wave B8 -- THE BLIND RE-SITS, and the two reports.

Nothing here fits anything. There is no optimiser in this file, no bounds and no
`least_squares` import. It runs two EXISTING scorers at frozen parameter sets and
assembles what they say.

THE DECOMPOSITION, AND IT IS THE POINT OF THE FILE
--------------------------------------------------
`d1_exam_panel_reconciliation.md` found that 96 % of the B2.2 -> B2.3 exam
regression was caused by an undeclared change of objective rather than by the
physics that wave shipped. B8 changes BOTH physics and parameters, so it scores
THREE columns and never two:

  PRE-B8      the artifacts already on disk at HEAD -- B2.3's vector under the
              pre-B8 code. This is what shipped before this wave.
  PHYSICS     B2.4-half's OWN vector, unrefitted, under B8's T-structure. The
              barriers moved; not one rate constant did.
  B8          B8's refitted vector under B8's T-structure. The ship.

PRE-B8 -> PHYSICS is what the measurements cost or bought on their own.
PHYSICS -> B8 is what the refit recovered. Reporting only the ends would let a
refit take credit for a measurement, or a measurement take the blame for a refit.

FIREWALL. `data/benchmarks/external_validation/` is opened by
`generate_cutover_final_exam` and by nothing else. This file reads the scorers'
own output.

Usage
-----
    python scripts/generators/generate_kinetic_core_b8_reports.py --all
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
if str(ROOT / "scripts" / "generators") not in sys.path:
    sys.path.insert(0, str(ROOT / "scripts" / "generators"))

V = ROOT / "results" / "validation"

B8_FIT = V / "kinetic_core_b8_fit_report.json"
B24_HALF_FIT = V / "kinetic_core_b2_4_fit_half.json"

#: PRE-B8 artifacts, as committed at HEAD. NOT regenerated by this wave.
#:
#: The panel baseline is B2.4-HALF's own, not B2.3's, and the choice matters:
#: B8 starts from B2.4-half's vector, so `pre_b8 -> physics_only` is then a
#: clean A/B on ONE vector in which only the code changed. B2.3's panel would
#: have moved both the vector and the code at once, which is the confusion D1
#: was written about. (B2.3's own report also predates B2.4's addition of the
#: continuous statistics, so half its cells would be empty.)
PRE_B8_PANEL = V / "kinetic_core_b2_4_panel_half.json"
#: The exam baseline is the SHIPPING one -- B2.3's vector under the pre-B8 code,
#: which is what a user got before this wave. B2.4's exam artifacts predate B7's
#: trunk change, so they are not like-for-like with anything B8 produces.
PRE_B8_EXAM = V / "cutover_final_exam.json"

PANEL_B8 = "kinetic_core_b8_panel"
PANEL_PHYSICS = "kinetic_core_b8_panel_physics_only"
EXAM_B8 = "kinetic_core_b8_exam"
EXAM_PHYSICS = "kinetic_core_b8_exam_physics_only"


# ===========================================================================
# 1. RUN THE TWO EXISTING SCORERS
# ===========================================================================


def run_panel(fit_report: Path, basename: str) -> Dict[str, Any]:
    import generate_kinetic_core_b2_3_holdout as PANEL
    PANEL.FIT_REPORT = fit_report
    PANEL.OUT_BASENAME = basename
    rc = PANEL.main(["--basename", basename])
    if rc != 0:
        raise SystemExit(f"panel returned {rc} for {fit_report}")
    return json.loads((V / f"{basename}.json").read_text())


def run_exam(fit_report: Path, basename: str) -> Dict[str, Any]:
    import generate_cutover_final_exam as EXAM
    from src.kinetic_core import engine
    previous = engine._B2_FIT_REPORT
    try:
        engine._B2_FIT_REPORT = fit_report
        payload = EXAM.build_exam(target_tag="meaty")
    finally:
        engine._B2_FIT_REPORT = previous
    payload["parameters_from"] = str(fit_report.relative_to(ROOT))
    payload["wave_column"] = basename
    (V / f"{basename}.json").write_text(
        json.dumps(payload, indent=2, sort_keys=True, default=str))
    (V / f"{basename}.md").write_text(EXAM.render_markdown(payload))
    return payload


# ===========================================================================
# 2. THE ASSEMBLY
# ===========================================================================


def _exam_row_map(payload: Dict[str, Any]) -> Dict[str, Dict[str, Any]]:
    out = {}
    for row in payload.get("rows", []):
        key = (row.get("benchmark_id"), row.get("compound"),
               row.get("temp_C"), row.get("time_min"))
        out[repr(key)] = row
    return out


def _fold(row: Optional[Dict[str, Any]]) -> Optional[float]:
    if row is None:
        return None
    v = row.get("core_fold_error")
    return float(v) if isinstance(v, (int, float)) else None


#: THE PRE-REGISTERED CLAIMS, SCORED MECHANICALLY.
#:
#: Every claim below is quoted from `kinetic_core_b8_prereg.md`, which was on
#: disk before any B8 member ran. Scoring them in CODE rather than in prose is
#: the point: a pre-registration that is graded by hand after the numbers are
#: seen is graded by someone who has seen the numbers. Where a claim cannot be
#: computed from the artifacts it is reported UNSCORED rather than argued.
def _prereg_scorecard(fit, panel_b8, panel_phys, panel_pre, exam_b8, exam_pre,
                      moved, checked) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []

    def claim(cid, text, outcome, verdict, detail=""):
        rows.append({"id": cid, "claim": text, "outcome": outcome,
                     "verdict": verdict, "detail": detail})

    t = fit["t_structure"]
    fr = fit["frozen_parameters"]
    thiol = t["thiol_sink_fitted_kj_mol"]
    claim("F-1",
          "Ea_decay_thiol_sink lands ON its new 102 ceiling (within 2 kJ/mol)",
          f"{thiol:.2f} kJ/mol -- {t['thiol_sink_band_state']}",
          "HELD" if t["thiol_sink_band_state"] == "ON THE CEILING"
          else "FALSIFIED",
          "Pre-registered at 60% BECAUSE it predicts the wave's own headline "
          "parameter coming back bound-limited again. B2.2/B2.3/B2.4 all wanted "
          "213-248.")

    shared = fit["objective"]["sum_r2_level_shared_with_b2_4"]
    b24_shared = 15.123046616117534
    worsened = shared > b24_shared
    in_band = 15.5 <= shared <= 25.0
    # COMPOUND CLAIM, SCORED COMPOUND. `kinetic_core_b2_2_diagnosis.md` sec. 2
    # caught a scorer marking a two-clause claim HELD because its check tested
    # only the numeric band; this one tests both clauses and says which failed.
    claim("F-2",
          "sum_r2_level on the shared rows WORSENS against B2.4-half's 15.123 "
          "AND lands in 15.5-25.0",
          f"{shared:.3f} (B2.4-half: {b24_shared:.3f}); "
          f"worsened: {'yes' if worsened else 'no'}; "
          f"in the 15.5-25.0 band: {'yes' if in_band else 'NO'}",
          "HELD" if (worsened and in_band)
          else "HALF-FALSIFIED" if worsened else "FALSIFIED",
          "The direction was right and the SIZE was badly underestimated: the "
          f"shared-row residual is {shared / b24_shared:.1f}x B2.4-half's, not "
          "the ~1.0-1.7x the band allowed. That gap IS the disagreement between "
          "the corpus's measured barriers and the fitted ones they replaced, "
          "and 23 free parameters could not absorb it.")

    lumped = fr["lumped_formation_Ea_kJ_mol"]
    claim("F-3", "the lumped formation Ea stays inside 40-100 kJ/mol",
          f"{lumped:.2f} kJ/mol",
          "HELD" if 40.0 <= lumped <= 100.0 else "FALSIFIED",
          "it was 64.08 in B2.3")

    best = min(fit["members"], key=lambda m: m["cost"])
    claim("F-6",
          "still <= 5 of 48 parameters carry a finite Gauss-Newton interval",
          "NOT COMPUTED -- B8's fit report does not evaluate intervals",
          "UNSCORED",
          "B2.3's report is the last artifact that computed them (3 of 48). "
          "Reported as unscored rather than assumed.")

    acc = panel_b8["scorecard"]["b8_retirement_accounting"]
    claim("H-1",
          "on the OLD basis B8's gating total is within +/-2 of B2.4-half's",
          f"old basis {acc['old_basis_gating_passed']} / "
          f"{acc['old_basis_gating_rows']} against B2.4-half "
          f"{panel_pre['scorecard']['gating_passed']} / "
          f"{panel_pre['scorecard']['gating_rows']}",
          "HELD" if abs(acc["old_basis_gating_passed"]
                        - panel_pre["scorecard"]["gating_passed"]) <= 2
          else "FALSIFIED")

    retired_failed = all(not r["pass_if_it_had_counted"] for r in acc["retired"])
    claim("H-2",
          "had they been scored, BOTH retired rows would still have FAILED",
          "; ".join(f"{r['id']}: "
                    f"{'PASS' if r['pass_if_it_had_counted'] else 'FAIL'}"
                    for r in acc["retired"]),
          "HELD" if retired_failed else "FALSIFIED",
          "reported scored-but-not-counted so the retirement is visibly not a "
          "rescue")

    def _row(payload, row_id):
        return next((r for r in payload["rows"] if r["id"] == row_id), None)

    at_risk = ("hofmann2002_brew_80C_FFT", "vanseeventer_50C_MFT_per_day")
    regressions = []
    for row_id in at_risk:
        before, after = _row(panel_pre, row_id), _row(panel_b8, row_id)
        if before is None or after is None:
            continue
        if before.get("pass") and not after.get("pass"):
            regressions.append(row_id)
    claim("H-3",
          "the two LOW-TEMPERATURE rows are at risk from the barrier drop; at "
          "least one regresses",
          f"regressed: {regressions or 'neither'}",
          "HELD" if regressions else "FALSIFIED",
          "The reasoning was that a thiol sink barrier falling from 216 to "
          "<= 102 with k_ref anchored at 145 C makes the sink relatively "
          "FASTER when cold -- the mechanism that destroyed both rows in B2. "
          "It did not happen, and the reason is visible in the fitted vector: "
          "the refit paid for the lower barrier by moving k_ref, so the sink's "
          "ABSOLUTE rate at 50-80 C did not rise. The price the wave expected "
          "to pay at low temperature was paid on the pH-8 column instead.")

    kang_fft = _row(panel_b8, "kang_140C_FFT")
    claim("H-4", "kang_140C_FFT stays failing",
          f"{'PASS' if kang_fft and kang_fft.get('pass') else 'FAIL'} at "
          f"{_fmt(kang_fft.get('fold_error') if kang_fft else None)}x",
          "HELD" if kang_fft and not kang_fft.get("pass") else "FALSIFIED")

    dimer_moves = []
    for ph_label in ("6", "7", "8"):
        rid = f"zhou_120C_dimer_share_pH{ph_label}"
        before, after = _row(panel_pre, rid), _row(panel_b8, rid)
        if not before or not after:
            continue
        b, c = before.get("fold_error"), after.get("fold_error")
        if isinstance(b, (int, float)) and isinstance(c, (int, float)) and b > 0:
            dimer_moves.append((rid, c / b))
    claim("H-5",
          "the three zhou_120C_dimer_share_pH* rows move by >= 1.5x in either "
          "direction (they are the only rows that directly score the dimer "
          "branch the T-structure re-barriers)",
          "; ".join(f"{rid} x{ratio:.2f}" for rid, ratio in dimer_moves)
          or "not scoreable",
          "HELD" if dimer_moves and all(
              ratio >= 1.5 or ratio <= 1 / 1.5 for _rid, ratio in dimer_moves)
          else "FALSIFIED")

    yil_pre = exam_pre["by_family"].get("sulfur_yiltirak2026_T_ladder", {})
    yil_b8 = exam_b8["by_family"].get("sulfur_yiltirak2026_T_ladder", {})
    yil_before = yil_pre.get("core_median_fold")
    yil_after = yil_b8.get("core_median_fold")
    claim("X-1",
          "THE HEADLINE -- the Yiltirak family median improves by >= 3x, to "
          "<= 65x",
          f"{_fmt(yil_before)}x -> {_fmt(yil_after)}x",
          "HELD" if (isinstance(yil_after, (int, float))
                     and isinstance(yil_before, (int, float))
                     and yil_after <= 65.0 and yil_after <= yil_before / 3.0)
          else "FALSIFIED",
          "The decay-turnover mechanism is the named candidate for its 0/8: a "
          "core whose sink barely runs cannot produce a peak, so it must "
          "over-predict every long hold.")
    claim("X-2", "Yiltirak enters the band on at least 1 of 8",
          f"{yil_b8.get('core_within_band')} / {yil_b8.get('answered')}",
          "HELD" if (yil_b8.get("core_within_band") or 0) >= 1 else "FALSIFIED")

    pre_paired = exam_pre["summary"]["paired_subset"]["core"]["median_fold_error"]
    b8_paired = exam_b8["summary"]["paired_subset"]["core"]["median_fold_error"]
    claim("X-3", "the exam's core paired median improves against 42.23x",
          f"{_fmt(pre_paired)}x -> {_fmt(b8_paired)}x",
          "HELD" if b8_paired < pre_paired else "FALSIFIED")

    hof_pre = exam_pre["by_family"].get("sulfur_hofmann1998_145C", {}).get(
        "core_median_fold")
    hof_b8 = exam_b8["by_family"].get("sulfur_hofmann1998_145C", {}).get(
        "core_median_fold")
    hof_ratio = (hof_b8 / hof_pre
                 if isinstance(hof_pre, (int, float)) and hof_pre > 0
                 and isinstance(hof_b8, (int, float)) else None)
    claim("X-4",
          "the sulfur_hofmann1998_145C family median moves by < 1.5x either way "
          "(its rows sit AT the k_ref reference temperature, where a barrier "
          "change is nearly inert by construction)",
          f"{_fmt(hof_pre)}x -> {_fmt(hof_b8)}x "
          f"(x{_fmt(hof_ratio, '{:.2f}')})",
          "HELD" if hof_ratio is not None and (1 / 1.5) < hof_ratio < 1.5
          else "FALSIFIED")

    claim("X-5",
          "the acrylamide, furanic and lipid families are BIT-IDENTICAL -- no "
          "B8 parameter touches them and the covalent retirement is "
          "documentation over a term that already contributed exactly 0.0",
          f"{checked} points checked, {len(moved)} moved",
          "HELD" if not moved else "FALSIFIED",
          "Named in the prereg sec. 4 as the first thing that would falsify "
          "the whole wave.")

    pre_declined = exam_pre["summary"].get("core_declined")
    b8_declined = exam_b8["summary"].get("core_declined")
    b8_answered = exam_b8["summary"].get("core_answered")
    claim("X-6",
          "the exam's declined points stay declined and the answered count "
          "stays 34",
          f"declined {pre_declined} -> {b8_declined}; answered {b8_answered}",
          "HELD" if (pre_declined == b8_declined and b8_answered == 34)
          else "FALSIFIED")

    predicted_fail = {
        "wang2026_MFT_peak_and_fall_125_over_115": "N-1",
        "wang2026_FFT_peak_and_fall_115_over_105": "N-2",
    }
    for row_id, cid in predicted_fail.items():
        row = _row(panel_b8, row_id)
        if row is None:
            continue
        predicted_value = row.get("predicted")
        observed_value = row.get("observed")
        falls = (isinstance(predicted_value, (int, float))
                 and predicted_value < 1.0)
        if row["pass"]:
            detail = (
                "★ A PRE-REGISTERED FAIL THAT PASSED, and it is the wave's best "
                "single result. The claim was that the model predicts a RISE "
                f"here; it predicts {_fmt(predicted_value)} against a measured "
                f"{_fmt(observed_value)} -- A FALL, inside the 2x band. THE "
                "TURNOVER EMERGED. This row is the reason the T-structure was "
                "built and it is reported as a falsified PREDICTION, not as a "
                "win: the wave was wrong about its own mechanism working.")
        else:
            detail = (
                "FAILED as pre-registered"
                + (f", but note the DIRECTION IS RIGHT: predicted "
                   f"{_fmt(predicted_value)} is below 1.0, i.e. a fall, against "
                   f"a measured {_fmt(observed_value)}. The model produces the "
                   "turnover and undersizes it; the claim said it would produce "
                   "a RISE, so the prediction held on the pass/fail column and "
                   "was wrong about the mechanism."
                   if falls else
                   ". The model predicts a rise where the measurement falls, "
                   "exactly as pre-registered."))
        claim(cid,
              f"`{row_id}` FAILS, and in a named direction (the model predicts "
              f"a RISE where the measurement falls)",
              f"{'PASS' if row['pass'] else 'FAIL'} at "
              f"{_fmt(row.get('fold_error'))}x "
              f"(predicted {_fmt(predicted_value)} against observed "
              f"{_fmt(observed_value)})",
              "HELD" if not row["pass"] else "FALSIFIED",
              detail)
    zhai_row = _row(panel_b8, "zhai_13C_exogenous_carbon_threshold")
    if zhai_row is not None:
        claim("N-3",
              "the 13C threshold is reported as a SCOPE GAP rather than as a "
              "pass or a fail",
              f"scored {'PASS' if zhai_row['pass'] else 'FAIL'} on the in-scope "
              f"proxy; comment states the scope gap: "
              f"{'yes' if 'SCOPE GAP' in (zhai_row.get('comment') or '') else 'NO'}",
              "HELD" if "SCOPE GAP" in (zhai_row.get("comment") or "")
              else "FALSIFIED")
    ames_row = _row(panel_b8, "ames2001_excess_Ea_class_split")
    if ames_row is not None:
        claim("N-4",
              "the excess-Ea SIGN SPLIT reproduces (MFT and FFT positive, "
              "2-acetylthiazole negative) in the module's aqueous pot",
              f"{'REPRODUCED' if ames_row['pass'] else 'NOT reproduced'}: "
              f"{ames_row.get('predicted')}",
              "HELD" if ames_row["pass"] else "FALSIFIED",
              "Pre-registered at 45% -- genuinely uncertain, and DIAGNOSTIC "
              "either way because Ames measures a low-moisture extrudate and "
              "this module has no matrix-transfer term.")
    return rows


def build_holdout_report() -> Dict[str, Any]:
    fit = json.loads(B8_FIT.read_text())
    panel_b8 = json.loads((V / f"{PANEL_B8}.json").read_text())
    panel_phys = json.loads((V / f"{PANEL_PHYSICS}.json").read_text())
    panel_pre = json.loads(PRE_B8_PANEL.read_text())
    exam_b8 = json.loads((V / f"{EXAM_B8}.json").read_text())
    exam_phys = json.loads((V / f"{EXAM_PHYSICS}.json").read_text())
    exam_pre = json.loads(PRE_B8_EXAM.read_text())

    def _panel_line(p):
        sc = p["scorecard"]
        return {
            "gating_passed": sc["gating_passed"],
            "gating_rows": sc["gating_rows"],
            "median_abs_log10_fold_gating": sc.get("median_abs_log10_fold_gating"),
            "geometric_mean_fold_gating": sc.get("geometric_mean_fold_gating"),
            "diagnostic_passed": sc.get("diagnostic_passed"),
            "diagnostic_rows": sc.get("diagnostic_rows"),
        }

    def _exam_line(p):
        s = p["summary"]
        return {
            "core_paired_median_fold": s["paired_subset"]["core"]["median_fold_error"],
            "core_geometric_mean_fold": s["core"].get("geometric_mean_fold"),
            "core_median_fold": s["core"]["median_fold_error"],
            "core_within_band": s["core_within_band"],
            "core_scored": s["core_scored"],
            "core_answered": s.get("core_answered"),
            "core_declined": s.get("core_declined"),
            "worst_fold": s["core"].get("worst_fold_error"),
        }

    families = {}
    for name in sorted(set(exam_b8["by_family"]) | set(exam_pre["by_family"])):
        pre = exam_pre["by_family"].get(name, {})
        phys = exam_phys["by_family"].get(name, {})
        new = exam_b8["by_family"].get(name, {})
        families[name] = {
            "pre_b8": {"median": pre.get("core_median_fold"),
                       "in_band": pre.get("core_within_band"),
                       "answered": pre.get("answered")},
            "physics_only": {"median": phys.get("core_median_fold"),
                             "in_band": phys.get("core_within_band"),
                             "answered": phys.get("answered")},
            "b8": {"median": new.get("core_median_fold"),
                   "in_band": new.get("core_within_band"),
                   "answered": new.get("answered")},
        }

    # THE X-5 CHECK, computed rather than asserted: which points moved at all.
    pre_rows = _exam_row_map(exam_pre)
    b8_rows = _exam_row_map(exam_b8)
    untouched_families = ("acrylamide_180C", "furan_browning_glc_alanine",
                          "matrix_path_lipid")
    moved: List[Dict[str, Any]] = []
    checked = 0
    for key, row in b8_rows.items():
        fam = str(row.get("family", ""))
        if fam not in untouched_families:
            continue
        before, after = _fold(pre_rows.get(key)), _fold(row)
        if before is None or after is None:
            continue
        checked += 1
        if before <= 0 or after <= 0:
            continue
        ratio = after / before
        if abs(ratio - 1.0) > 1e-9:
            moved.append({"point": key, "family": fam, "pre_b8": before,
                          "b8": after, "ratio": ratio})

    # ------------------------------------------------------------------
    # THE YILTIRAK VERDICT, POINT BY POINT
    # ------------------------------------------------------------------
    # The family the whole T-structure was aimed at. A family median hides the
    # thing that matters here, because the two compounds behave differently and
    # the median is set by whichever has more points on the wrong side.
    yiltirak = []
    for key, row in b8_rows.items():
        if row.get("family") != "sulfur_yiltirak2026_T_ladder":
            continue
        before, after = _fold(pre_rows.get(key)), _fold(row)
        phys = _fold(_exam_row_map(exam_phys).get(key))
        yiltirak.append({
            "compound": row.get("compound"),
            "temp_C": row.get("temp_C"), "time_min": row.get("time_min"),
            "pre_b8": before, "physics_only": phys, "b8": after,
            "improvement_x": (before / after
                              if before and after and after > 0 else None),
            "within_band": row.get("core_within_band"),
        })
    yiltirak.sort(key=lambda r: (str(r["compound"]), r["temp_C"] or 0))
    improved = [r for r in yiltirak
                if r["improvement_x"] and r["improvement_x"] > 1.0]
    by_compound = {}
    for r in yiltirak:
        by_compound.setdefault(str(r["compound"]), []).append(r)
    compound_median = {
        name: sorted(x["improvement_x"] for x in rows_
                     if x["improvement_x"])[len(rows_) // 2]
        for name, rows_ in by_compound.items()
        if any(x["improvement_x"] for x in rows_)
    }

    new_holdouts = [
        r for r in panel_b8["rows"]
        if r["id"] in (
            "wang2026_MFT_peak_and_fall_125_over_115",
            "wang2026_FFT_peak_and_fall_115_over_105",
            "zhai_13C_exogenous_carbon_threshold",
            "ames2001_excess_Ea_class_split",
        )
    ]

    scorecard = _prereg_scorecard(
        fit, panel_b8, panel_phys, panel_pre, exam_b8, exam_pre, moved, checked)

    payload = {
        "wave": "B8 -- blind re-sits (Amendments 16, 17, 18)",
        "prereg_scorecard": scorecard,
        "generated_by": "scripts/generators/generate_kinetic_core_b8_reports.py",
        "prereg": "results/validation/kinetic_core_b8_prereg.md",
        "columns": {
            "pre_b8": (
                "The artifacts already on disk at HEAD. PANEL: B2.4-half's own "
                "vector under the pre-B8 code, so `pre_b8 -> physics_only` is a "
                "clean A/B on ONE vector in which only the code changed. EXAM: "
                "B2.3's vector under the pre-B8 code, which is what shipped "
                "before this wave -- B2.4's exam artifacts predate B7's trunk "
                "change and are not like-for-like with anything B8 produces, "
                "so the exam's pre-B8 column carries a vector change as well "
                "as a code change and is read as a SHIPPING comparison rather "
                "than as a controlled one."),
            "physics_only": (
                "B2.4-half's OWN vector, UNREFITTED, under B8's T-structure. "
                "The FOUR MEASURED BARRIERS apply (k_dimer_mft and k_dimer_fft "
                "at 122.2 where they had none, k_arp_dpo and k_arp_tdp at 85.7 "
                "instead of the lumped 64.08); not one rate constant moves. "
                "NOTE, PRECISELY: this column keeps B2.4-half's OWN "
                "`Ea_decay_thiol_sink` of 215.7 -- Gigl's (7, 102) band is a "
                "constraint on the SEARCH and B2.4 was not searched under it, "
                "so clipping it here would mix the measurements in with the "
                "band and blunt the decomposition. pre-B8 -> physics is "
                "therefore the four measured barriers ALONE; physics -> B8 is "
                "the refit, which is also where the thiol sink enters its "
                "band."),
            "b8": "B8's refitted vector under B8's T-structure -- the ship",
        },
        "why_three_columns": (
            "d1_exam_panel_reconciliation.md found 96% of the B2.2 -> B2.3 exam "
            "regression was an undeclared objective change rather than the "
            "physics that wave shipped. B8 changes BOTH, so reporting only the "
            "ends would let the refit take credit for the measurements or the "
            "measurements take the blame for the refit."
        ),
        "panel": {
            "pre_b8": _panel_line(panel_pre),
            "physics_only": _panel_line(panel_phys),
            "b8": _panel_line(panel_b8),
            "b8_retirement_accounting": (
                panel_b8["scorecard"]["b8_retirement_accounting"]),
            "gating_trajectory": panel_b8["gating_trajectory"],
        },
        "exam": {
            "pre_b8": _exam_line(exam_pre),
            "physics_only": _exam_line(exam_phys),
            "b8": _exam_line(exam_b8),
            "by_family": families,
        },
        "x5_untouched_family_check": {
            "families": list(untouched_families),
            "points_checked": checked,
            "points_that_moved": moved,
            "verdict": ("BIT-IDENTICAL" if not moved
                        else "MOVED -- see points_that_moved"),
            "why_it_matters": (
                "No acrylamide, furanic or lipid parameter is touched by B8, "
                "and the covalent-sink retirement is documentation over a term "
                "that already contributed exactly 0.0. Pre-registered as X-5: "
                "if any of these moves, the retirement was not the no-op this "
                "wave claims and that is a finding, not a rounding error."
            ),
        },
        "yiltirak_verdict": {
            "points": yiltirak,
            "n_improved": len(improved),
            "n_points": len(yiltirak),
            "median_improvement_by_compound_x": compound_median,
            "still_in_band": sum(1 for r in yiltirak if r["within_band"]),
            "verdict": (
                "The mechanism appears and it is NOT ENOUGH. Every one of the "
                "eight points improves, none enters the band, and the "
                "improvement is strongly ASYMMETRIC between the two thiols -- "
                "which is the informative part, because the same asymmetry "
                "shows up independently on the Wang replacement hold-outs: MFT's "
                "turnover reproduces (predicted 0.36 against a measured 0.30, "
                "inside the band) and FFT's does not (predicted 0.81 against a "
                "measured 0.15). Two scorers, two laboratories, one conclusion: "
                "B8's T-structure gives MFT the peak-and-decline the corpus "
                "measures and leaves FFT's sink far too weak. The remaining "
                "FFT error is therefore localised rather than diffuse, and it "
                "is localised on the FURFURAL LIMB -- the leg where Wang "
                "measures the precursor SATURATING while the thiol collapses."),
        },
        "replacement_holdouts": [
            {"id": r["id"], "gating": r["gating"], "pass": r["pass"],
             "fold_error": r.get("fold_error"), "observed": r.get("observed"),
             "predicted": r.get("predicted"),
             "why_it_cannot_gate": r.get("seen_diagnostic"),
             "comment": r.get("comment")}
            for r in new_holdouts
        ],
        "t_structure": fit["t_structure"],
        "objective": fit["objective"],
        "free_set": {"n_free": fit["free_set"]["n_free"],
                     "n_frozen": fit["free_set"]["n_frozen"]},
    }
    (V / "kinetic_core_b8_holdout_report.json").write_text(
        json.dumps(payload, indent=2, default=str))
    return payload


def _fmt(value, spec="{:.3g}", dash="--"):
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        return dash
    # NaN is what a row with no fold error carries -- a directional or
    # sign-test row. Printing "nanx" reads as a broken number; printing "--"
    # reads as what it is, which is "this row does not have a fold".
    if value != value or value in (float("inf"), float("-inf")):
        return dash
    return spec.format(value)


def render_holdout_markdown(payload: Dict[str, Any]) -> str:
    out: List[str] = []
    a = out.append
    a("# Build Wave B8 -- blind re-sits")
    a("")
    a("Pre-registered in `results/validation/kinetic_core_b8_prereg.md`, which "
      "was written and saved to disk BEFORE any B8 fit member ran and BEFORE "
      "any scorer was re-run. Nothing in this file fits anything.")
    a("")
    a("## Three columns, not two")
    a("")
    a(payload["why_three_columns"])
    a("")
    for key, description in payload["columns"].items():
        a(f"- **{key}** -- {description}")
    a("")

    a("## Pre-registration scorecard -- every claim, held or not")
    a("")
    a("Scored MECHANICALLY, in code, from the artifacts. A pre-registration "
      "graded by hand after the numbers are seen is graded by someone who has "
      "seen the numbers.")
    a("")
    a("| # | claim | outcome | verdict |")
    a("|---|---|---|---|")
    for row in payload["prereg_scorecard"]:
        a(f"| **{row['id']}** | {row['claim']} | {row['outcome']} | "
          f"**{row['verdict']}** |")
    a("")
    for row in payload["prereg_scorecard"]:
        if row.get("detail"):
            a(f"- **{row['id']}** ({row['verdict']}): {row['detail']}")
    a("")

    a("## The hold-out panel")
    a("")
    a("| statistic | pre-B8 | physics only | **B8** |")
    a("|---|---:|---:|---:|")
    p = payload["panel"]
    a(f"| gating | {p['pre_b8']['gating_passed']} / "
      f"{p['pre_b8']['gating_rows']} | "
      f"{p['physics_only']['gating_passed']} / "
      f"{p['physics_only']['gating_rows']} | "
      f"**{p['b8']['gating_passed']} / {p['b8']['gating_rows']}** |")
    a(f"| median \\|log10 fold\\| (gating) | "
      f"{_fmt(p['pre_b8']['median_abs_log10_fold_gating'])} | "
      f"{_fmt(p['physics_only']['median_abs_log10_fold_gating'])} | "
      f"**{_fmt(p['b8']['median_abs_log10_fold_gating'])}** |")
    a(f"| geometric-mean fold (gating) | "
      f"{_fmt(p['pre_b8']['geometric_mean_fold_gating'])}x | "
      f"{_fmt(p['physics_only']['geometric_mean_fold_gating'])}x | "
      f"**{_fmt(p['b8']['geometric_mean_fold_gating'])}x** |")
    a(f"| diagnostic | {p['pre_b8']['diagnostic_passed']} / "
      f"{p['pre_b8']['diagnostic_rows']} | "
      f"{p['physics_only']['diagnostic_passed']} / "
      f"{p['physics_only']['diagnostic_rows']} | "
      f"**{p['b8']['diagnostic_passed']} / {p['b8']['diagnostic_rows']}** |")
    a("")
    a("⚠️ **THE DENOMINATORS ARE NOT THE SAME ACROSS COLUMNS.** The pre-B8 "
      "column is the panel as it stood at HEAD; the two B8 columns run the "
      "post-Amendment-17 panel, which RETIRES two gating rows and adds four "
      "rows that cannot gate. The retirement accounting immediately below "
      "gives both bases on the same scorer so the change is checkable.")
    a("")
    acc = p["b8_retirement_accounting"]
    a("### Retirement accounting -- BOTH BASES")
    a("")
    a("| basis | gating |")
    a("|---|---:|")
    a(f"| OLD (the two `kang_switch_on_*` rows counted, exactly as they scored) "
      f"| **{acc['old_basis_gating_passed']} / "
      f"{acc['old_basis_gating_rows']}** |")
    a(f"| NEW (post-retirement) | **{acc['new_basis_gating_passed']} / "
      f"{acc['new_basis_gating_rows']}** |")
    a("")
    for r in acc["retired"]:
        a(f"- RETIRED: `{r['id']}` -- would have "
          f"{'PASSED' if r['pass_if_it_had_counted'] else 'FAILED'} at "
          f"{_fmt(r.get('fold_error'))}x.")
    a(f"- **Rows added back into the gating total: "
      f"{acc['gating_rows_added_back']}.** The three replacement hold-outs are "
      f"seen-by-extraction and may never gate, so the denominator genuinely "
      f"falls by {acc['gating_rows_removed_by_retirement']}.")
    a("")

    a("## The both-ways cutover exam")
    a("")
    e = payload["exam"]
    a("| statistic | pre-B8 | physics only | **B8** |")
    a("|---|---:|---:|---:|")
    for label, key in (
        ("core paired median fold", "core_paired_median_fold"),
        ("core geometric-mean fold", "core_geometric_mean_fold"),
        ("core median fold (all)", "core_median_fold"),
        ("worst fold", "worst_fold"),
    ):
        a(f"| {label} | {_fmt(e['pre_b8'][key])}x | "
          f"{_fmt(e['physics_only'][key])}x | **{_fmt(e['b8'][key])}x** |")
    a(f"| in band | {e['pre_b8']['core_within_band']} / "
      f"{e['pre_b8']['core_scored']} | "
      f"{e['physics_only']['core_within_band']} / "
      f"{e['physics_only']['core_scored']} | "
      f"**{e['b8']['core_within_band']} / {e['b8']['core_scored']}** |")
    a(f"| answered / declined | {e['pre_b8']['core_answered']} / "
      f"{e['pre_b8']['core_declined']} | "
      f"{e['physics_only']['core_answered']} / "
      f"{e['physics_only']['core_declined']} | "
      f"**{e['b8']['core_answered']} / {e['b8']['core_declined']}** |")
    a("")
    a("### By family")
    a("")
    a("| family | pre-B8 median | physics only | **B8 median** | in band (B8) |")
    a("|---|---:|---:|---:|---:|")
    for name, block in e["by_family"].items():
        a(f"| `{name}` | {_fmt(block['pre_b8']['median'])}x | "
          f"{_fmt(block['physics_only']['median'])}x | "
          f"**{_fmt(block['b8']['median'])}x** | "
          f"{block['b8']['in_band']} / {block['b8']['answered']} |")
    a("")

    x5 = payload["x5_untouched_family_check"]
    a("### X-5 -- the three families no B8 parameter touches")
    a("")
    a(x5["why_it_matters"])
    a("")
    a(f"**{x5['points_checked']} points checked across "
      f"{', '.join('`' + f + '`' for f in x5['families'])}. "
      f"VERDICT: {x5['verdict']}.**")
    if x5["points_that_moved"]:
        a("")
        a("| point | family | pre-B8 | B8 | ratio |")
        a("|---|---|---:|---:|---:|")
        for row in x5["points_that_moved"]:
            a(f"| `{row['point']}` | `{row['family']}` | "
              f"{_fmt(row['pre_b8'])}x | {_fmt(row['b8'])}x | "
              f"{_fmt(row['ratio'], '{:.4f}')} |")
    a("")

    y = payload["yiltirak_verdict"]
    a("## The Yiltirak family -- the verdict, point by point")
    a("")
    a("| compound | T (C) | t (min) | pre-B8 | physics only | **B8** | improvement |")
    a("|---|---:|---:|---:|---:|---:|---:|")
    for row in y["points"]:
        a(f"| {row['compound']} | {_fmt(row['temp_C'], '{:.0f}')} | "
          f"{_fmt(row['time_min'], '{:.0f}')} | {_fmt(row['pre_b8'])}x | "
          f"{_fmt(row['physics_only'])}x | **{_fmt(row['b8'])}x** | "
          f"{_fmt(row['improvement_x'], '{:.2f}')}x |")
    a("")
    a(f"**{y['n_improved']} of {y['n_points']} points improved; "
      f"{y['still_in_band']} entered the band.** Median improvement by "
      "compound: "
      + ", ".join(f"{name} {value:.2f}x"
                  for name, value in y["median_improvement_by_compound_x"].items())
      + ".")
    a("")
    a(y["verdict"])
    a("")

    a("## The three replacement hold-outs")
    a("")
    a("All are `seen_diagnostic` and **none gates.** Each carries a written, "
      "quantitative prediction made before this scorer existed "
      "(`kinetic_core_b8_prereg.md` sec. 3, rows N-1 to N-4).")
    a("")
    a("| row | gates | result | fold |")
    a("|---|---|---|---:|")
    for row in payload["replacement_holdouts"]:
        a(f"| `{row['id']}` | {'yes' if row['gating'] else '**no**'} | "
          f"{'PASS' if row['pass'] else '**FAIL**'} | "
          f"{_fmt(row.get('fold_error'))}x |")
    a("")
    for row in payload["replacement_holdouts"]:
        a(f"### `{row['id']}`")
        a("")
        a(f"- observed: `{row['observed']}`")
        a(f"- predicted: `{row['predicted']}`")
        a(f"- cannot gate because: {row['why_it_cannot_gate']}")
        a(f"- {row['comment']}")
        a("")

    a("## The T-structure, as fitted")
    a("")
    t = payload["t_structure"]
    a(f"- `Ea_decay_thiol_sink` = **{_fmt(t['thiol_sink_fitted_kj_mol'], '{:.2f}')} "
      f"kJ/mol**, in the declared band "
      f"{t['thiol_sink_band_kj_mol']} around a prior centre of "
      f"{t['thiol_sink_prior_centre_kj_mol']} -- "
      f"**{t['thiol_sink_band_state']}**.")
    a(f"- `Ea_decay_carbonyl_sink` = "
      f"**{_fmt(t['carbonyl_sink_fitted_kj_mol'], '{:.2f}')} kJ/mol** in "
      f"{t['carbonyl_sink_band_kj_mol']} -- **{t['carbonyl_sink_band_state']}** "
      f"(UNCHANGED band; K6a measured no carbonyl-sink barrier).")
    a("- Measured barriers the fit cannot move: "
      + ", ".join(f"`{k}` = {v}" for k, v in
                  t["measured_barriers_the_fit_cannot_move"].items()) + ".")
    a("")
    a(f"**REFUTED:** {t['refuted']}")
    a("")
    a(f"*Objective: {payload['objective']['n_rows']} declared FIT rows "
      f"({payload['objective']['n_new_rows']} new in B8), "
      f"{payload['free_set']['n_free']} free of "
      f"{payload['free_set']['n_free'] + payload['free_set']['n_frozen']} "
      f"parameters. {payload['objective']['not_comparable_note']}*")
    return "\n".join(out) + "\n"


def render_fit_markdown() -> str:
    fit = json.loads(B8_FIT.read_text())
    out: List[str] = []
    a = out.append
    a("# Build Wave B8 -- the fit")
    a("")
    a("Pre-registered in `results/validation/kinetic_core_b8_prereg.md`. The "
      "final parameter wave of the kinetic-core rebuild: it implements "
      "Amendments 16 and 17 and refits the sulfur lane on the updated FIT set "
      "at the single declared weighting B2.4's own exam-blind and panel-blind "
      "criterion shipped.")
    a("")
    o = fit["objective"]
    a("## The objective")
    a("")
    a(f"- **{o['n_rows']} declared FIT rows** "
      f"({o['n_rows_in_b2_4']} of them B2.4's, {o['n_new_rows']} new: "
      + ", ".join(f"`{r}`" for r in o["new_row_ids"]) + ")")
    a(f"- **{o['n_free_parameters']} free of "
      f"{o['n_free_parameters'] + o['n_frozen']}**")
    a(f"- pH exchange rate **E = {o['ph_endpoint_weight_E_decades_per_pH_unit']}** "
      f"(sigma_ph = {_fmt(o['sigma_ph_units'])} pH units)")
    a(f"- final cost **{_fmt(o['final_cost'], '{:.4f}')}**")
    a(f"- `sum_r2_level` on the rows B2.4 also scored: "
      f"**{_fmt(o['sum_r2_level_shared_with_b2_4'], '{:.3f}')}**; on all B8 "
      f"rows: {_fmt(o['sum_r2_level_all_b8_rows'], '{:.3f}')}")
    a("")
    a(o["not_comparable_note"])
    a("")
    a("## The members")
    a("")
    a("| start | arm | start cost | final cost | evals | status | converged | s |")
    a("|---|---|---:|---:|---:|---:|---|---:|")
    for m in fit["members"]:
        a(f"| {m['start']} | {m['arm']} | {_fmt(m['start_cost'], '{:.3f}')} | "
          f"{_fmt(m['cost'], '{:.4f}')} | {m['evals']} | {m['status']} | "
          f"{'yes' if m['converged'] else 'NO'}"
          f"{' (BUDGET-EXHAUSTED)' if m.get('budget_exhausted') else ''} | "
          f"{_fmt(m['seconds'], '{:.0f}')} |")
    a("")
    a(f"Best: start **{fit['best_start']}**.")
    a("")
    t = fit["t_structure"]
    a("## The T-structure")
    a("")
    a("| barrier | band | prior centre | fitted | state |")
    a("|---|---|---:|---:|---|")
    a(f"| `Ea_decay_thiol_sink` (covalent capture) | "
      f"{t['thiol_sink_band_kj_mol']} | "
      f"{t['thiol_sink_prior_centre_kj_mol']} | "
      f"**{_fmt(t['thiol_sink_fitted_kj_mol'], '{:.2f}')}** | "
      f"**{t['thiol_sink_band_state']}** |")
    a(f"| `Ea_decay_carbonyl_sink` | {t['carbonyl_sink_band_kj_mol']} | -- | "
      f"**{_fmt(t['carbonyl_sink_fitted_kj_mol'], '{:.2f}')}** | "
      f"{t['carbonyl_sink_band_state']} |")
    a("")
    a("Measured barriers the fit cannot move:")
    a("")
    a("| step | Ea (kJ/mol) |")
    a("|---|---:|")
    for key, value in t["measured_barriers_the_fit_cannot_move"].items():
        a(f"| `{key}` | {value} |")
    a("")
    a(f"**REFUTED:** {t['refuted']}")
    a("")
    a("## The frozen vector")
    a("")
    fr = fit["frozen_parameters"]
    a(f"- lumped formation Ea: "
      f"**{_fmt(fr['lumped_formation_Ea_kJ_mol'], '{:.2f}')} kJ/mol**")
    a(f"- pH drift: acid yield "
      f"{_fmt(fr['ph_drift']['acid_yield_per_sink_event'], '{:.4f}')}, "
      f"ARP ammonium pKa "
      f"{_fmt(fr['ph_drift']['arp_secondary_ammonium_pKa'], '{:.3f}')}")
    a("")
    a("| log10 k_ref at 145 C | value |")
    a("|---|---:|")
    for key in sorted(fr["log10_k_ref_at_145C"]):
        a(f"| `{key}` | {_fmt(fr['log10_k_ref_at_145C'][key], '{:.3f}')} |")
    a("")
    a("## Bound adjacency -- what is estimated and what is only bounded")
    a("")
    a("A parameter pressed against a bound is not an estimate, and a report "
      "that prints it like one is misleading. Checked on every coordinate the "
      "fit was free to move:")
    a("")
    a("| coordinate | bounds | fitted | state |")
    a("|---|---|---:|---|")
    drift = fit["frozen_parameters"]["ph_drift"]
    checks = [
        ("Ea_decay_thiol_sink", t["thiol_sink_band_kj_mol"],
         t["thiol_sink_fitted_kj_mol"], 2.0),
        ("Ea_decay_carbonyl_sink", t["carbonyl_sink_band_kj_mol"],
         t["carbonyl_sink_fitted_kj_mol"], 2.0),
        ("ph_acid_yield_per_sink_event", [0.0, 1.0],
         drift["acid_yield_per_sink_event"], 1e-3),
        ("ph_arp_secondary_ammonium_pKa", [5.0, 11.0],
         drift["arp_secondary_ammonium_pKa"], 0.05),
    ]
    for name, (lo, hi), value, tol in checks:
        if abs(value - hi) <= tol:
            state = "**ON THE CEILING -- bound-limited, not an estimate**"
        elif abs(value - lo) <= tol:
            state = "**ON THE FLOOR -- bound-limited, not an estimate**"
        else:
            state = "interior"
        a(f"| `{name}` | [{lo}, {hi}] | {_fmt(value, '{:.4g}')} | {state} |")
    a("")
    a("- `Ea_decay_thiol_sink` is on its ceiling for the FOURTH consecutive "
      "wave (248 against 250, 216, 213-218, now 102 against 102). The band "
      "changed; the objective's appetite did not. It still wants more "
      "temperature dependence on the thiol sink than the measurement allows, "
      "and B8 does not widen the band to give it: Gigl's range is a "
      "measurement, the conflict is real, and it is reported rather than "
      "dissolved.")
    a("- `ph_acid_yield_per_sink_event` sits at ~4e-6 against a floor of 0. "
      "This is NOT new in B8: B2.4-half was already at ~1e-4, having come down "
      "from B2.3's 0.968. The pH trajectory is now driven almost entirely by "
      "the ARP ammonium pKa rather than by acid production, and that constant "
      "is a fitted nuisance parameter living in a pKa slot -- "
      "`kinetic_core_b2_2_diagnosis.md` sec. 5 item 2 says so and it is still "
      "true. **Neither may be quoted as an acid-base constant.**")
    a("- No parameter interval is computed by this wave, so `identified` is "
      "unknown for all 48. B2.3's report is the last artifact that evaluated "
      "them and found 3 of 48. Nothing in B8 adds identifiability: it removes "
      "freedom (four barriers become immovable) and adds four rows.")
    a("")
    a("*The blind re-sits are in "
      "`results/validation/kinetic_core_b8_holdout_report.md`. No score in "
      "that file entered any choice made in this one.*")
    return "\n".join(out) + "\n"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--all", action="store_true")
    parser.add_argument("--panels", action="store_true")
    parser.add_argument("--exams", action="store_true")
    parser.add_argument("--assemble", action="store_true")
    args = parser.parse_args(argv)
    do_all = args.all or not (args.panels or args.exams or args.assemble)

    if do_all or args.panels:
        run_panel(B24_HALF_FIT, PANEL_PHYSICS)
        run_panel(B8_FIT, PANEL_B8)
    if do_all or args.exams:
        run_exam(B24_HALF_FIT, EXAM_PHYSICS)
        run_exam(B8_FIT, EXAM_B8)
    if do_all or args.assemble:
        payload = build_holdout_report()
        (V / "kinetic_core_b8_holdout_report.md").write_text(
            render_holdout_markdown(payload))
        (V / "kinetic_core_b8_fit_report.md").write_text(render_fit_markdown())
        print("wrote kinetic_core_b8_{fit_report,holdout_report}.{md,json}")
        print(f"  X-5: {payload['x5_untouched_family_check']['verdict']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
