[pytest]
markers =
    regression: marks tests as regression tests (deselect with '-m "not regression"')
    slow: marks tests as slow (deselect with '-m "not slow"')
pythonpath = .
filterwarnings =
    ignore:.*torch.jit.*:DeprecationWarning
    ignore:.*Environment variable TORCH_FORCE_NO_WEIGHTS_ONLY_LOAD.*:UserWarning
    ignore:.*Log flushes by default now.*:FutureWarning
    ignore:Implicitly cleaning up <_TemporaryFileWrapper.*:ResourceWarning
