"""
src/kinetic_core/species_sulfur.py

THE SULFUR EXTENSION OF THE STATE VECTOR (Build Wave B2), WITH ITS CARBON,
NITROGEN AND SULFUR BOOKKEEPING.
=============================================================================

Build Wave B1 declared thirteen sulfur-free trunk species in ``species.py``.
This module APPENDS the sulfur block and publishes the CONCATENATED table.
Nothing in B1's table is edited, reordered or removed: the first
``len(SPECIES)`` entries of ``SULFUR_STATE`` are B1's, in B1's order, so a
trunk state vector is a prefix of a sulfur state vector and every B1 index is
still valid.

WHY THREE ACCOUNTING POOLS AND TWO SITE POOLS
---------------------------------------------
B1 routes unmeasured carbon into ``FRAG_C`` rather than deleting it. The sulfur
network needs the same discipline on two more elements and on two things that
are not elements at all:

  * ``FRAG_N`` / ``FRAG_S`` -- unassigned fragment nitrogen and sulfur. Cysteine
    thermolysis reports the H2S and nothing else; thiamine cleavage reports the
    C5 sulfur fragment and nothing else. The other atoms exist. They go here so
    the S and N invariants close as EQUALITIES.

  * ``MELE`` -- the MATRIX ELECTROPHILE SITE POOL, and ``OX`` -- OXIDANT
    EQUIVALENTS. Both carry ZERO atoms of every element, because neither is a
    molecule: ``MELE`` is a titrated site density (Charles-Bernard 2005:
    8-10 mmol per g dry coffee solids, by hydroxylamine titration) and ``OX``
    is a redox equivalent. They are declared ``role='site'`` and are exempt from
    nothing -- they balance trivially because they contain nothing. Their
    purpose is that both are DEPLETABLE, which is what makes the thiol sink a
    bimolecular, saturating channel rather than an eternal first-order drain.
    That distinction is the whole content of the Hofmann-2002 80 C brew
    hold-out, whose measured anomaly (the brew is SLOWER than the 30 C model
    systems) the dossier attributes to exactly this pool being partly consumed
    during extraction.

WHAT IS *NOT* HERE
------------------
Pyrazines, Sotolon, 2-acetyl-1-pyrroline, butane-2,3-dione and the thiazole
family beyond 2-acetylthiazole. They are declared out of scope for this wave in
``sulfur.py``'s OUT_OF_SCOPE block, with the FIT rows they strand named.

UNITS: mmol/L, minutes, Kelvin, kJ/mol -- B1's units, unchanged.
"""

from __future__ import annotations

from typing import Dict, Mapping, Tuple

from .species import SPECIES, Species

# ---------------------------------------------------------------------------
# The sulfur block
# ---------------------------------------------------------------------------
# Molecular weights are carried alongside because every absolute anchor in the
# sulfur corpus is printed in ug/L or ug per volume, and the network runs in
# mmol/L. The conversion is arithmetic, not a parameter, but it is a place a
# factor of 1000 can hide, so it lives in one table and is unit-tested.

SULFUR_SPECIES: Tuple[Species, ...] = (
    # ---- precursors -------------------------------------------------------
    Species("PENT", "aldopentose (D-ribose / D-xylose)", 5, 0, "reactant", True,
            "ONE generic aldopentose. The corpus measures ribose and xylose "
            "separately (Hofmann 1998 T1 pH 5: MFT 198 vs 143 ppb, FFT 121 vs "
            "96 ppb -- 1.38x and 1.26x apart) and this module CANNOT tell them "
            "apart. That is a declared limitation, not an oversight: no step in "
            "the corpus is measured separately for the two sugars, so a "
            "per-sugar rate constant would be fitted to exactly the two numbers "
            "it then reproduces. The 1.38x gap is reported as a fit residual.",
            sulfur=0),
    Species("Cys", "L-cysteine", 3, 1, "reactant", True,
            "BOTH the amine of the Maillard trunk AND the sulfur donor. It is "
            "consumed by three competing routes -- thermolysis to H2S, the "
            "Nedvidek 1,4-dideoxyosone step (in which the amino acid is a "
            "REAGENT, not a catalyst), and 2-acetylthiazole formation -- and "
            "regenerated by the enolisation steps it catalyses. That "
            "competition is where the pH-7 MFT maximum comes from.",
            sulfur=1),
    Species("THI", "thiamine (vitamin B1)", 12, 4, "reactant", True,
            "The second, independent MFT route. Cerny 2007b measures the "
            "thiamine:sugar split at 54:46 in the full ternary and >99:<1 / "
            "<5:>95 in the two single-route controls.",
            sulfur=1),
    # ---- sulfur-free intermediates ---------------------------------------
    Species("H2S", "hydrogen sulfide (total sulfide pool)", 0, 0, "intermediate", True,
            "TOTAL sulfide. The pH speciation into the reactive NEUTRAL H2S is "
            "applied at rate-evaluation time from the aqueous pKa, not stored.",
            sulfur=1),
    Species("ARP", "Amadori compound of a pentose (N-(1-deoxy-D-xylulos-1-yl)-alanine)",
            8, 1, "reactant", True,
            "Zhou 2023's FEED: purified ARP at 20 mmol/L, the fed-Amadori "
            "initial condition the corpus had never had. It is a REACTANT here, "
            "not an intermediate, because Zhou charges it directly. It "
            "partitions between the two enolisations exactly as a free sugar "
            "does -- which is why FFT (acid lane) and MFT (base lane) move in "
            "OPPOSITE pH directions in Zhou's own Table 1."),
    Species("DPO", "1-deoxypentosone (2,3-enolisation product)", 5, 0, "intermediate", False),
    Species("TDP", "3-deoxypentosone / 3-deoxyribosulose (1,2-enolisation product)",
            5, 0, "intermediate", True,
            "MEASURED as a FED precursor: Hofmann 1998 T3 feeds it with H2S and "
            "gets FFT at 0.08 mol%."),
    Species("DDP", "1,4-dideoxypentosone (the intact-C5 MFT precursor)", 5, 0,
            "intermediate", False,
            "Nedvidek 1992 Scheme 3: 1-deoxyosone + alpha-amino acid -> "
            "1,4-dideoxyosone + RCHO + CO2 + NH3. Cerny 2003 T2 makes this the "
            "DOMINANT MFT route: 49% unlabelled / 46% 13C5 with no fragment "
            "pattern, i.e. ~93% of MFT carries the INTACT pentose skeleton."),
    Species("NF", "norfuraneol (4-hydroxy-5-methyl-3(2H)-furanone)", 5, 0,
            "intermediate", True,
            "Measured in situ at 54 530 ug/100 mL = 4.78 mmol/L from ribose "
            "(Hofmann 1998 T5) -- 2750x the MFT in the same pot, which is the "
            "authors' own reason for doubting NF as THE key MFT intermediate."),
    Species("PTR", "2,3,4-pentanetrione", 5, 0, "intermediate", False,
            "The OTHER half of the 1-deoxypentosone partition (Nedvidek 1992 "
            "Scheme 2, verified by two negative controls). It exists so that "
            "funnelling the whole 1-deoxyosone pool into norfuraneol -- which "
            "over-supplies everything downstream -- is impossible by "
            "construction."),
    Species("FUR", "2-furaldehyde (furfural)", 5, 0, "intermediate", True),
    Species("HA", "hydroxyacetaldehyde (the C2 fragment)", 2, 0, "intermediate", False),
    # ---- sulfur-bearing intermediates and products ------------------------
    Species("MP", "1-mercapto-2-propanone (the C3 fragment)", 3, 0, "intermediate", True,
            "Hofmann 1998 T7: 2-oxopropanal + H2S gives 1.8 mol% at 1:1 and "
            "4.0 mol% at 1:2. Doubling H2S gives 2.2x product -- SUPER-linear.",
            sulfur=1),
    Species("HMP", "5-hydroxy-3-mercapto-2-pentanone (thiamine's MFT precursor)",
            5, 0, "intermediate", False, sulfur=1),
    Species("MESH", "methanethiol", 1, 0, "intermediate", True, sulfur=1),
    Species("MFT", "2-methyl-3-furanthiol", 5, 0, "product", True,
            "odour threshold 0.005 ug/L in water (Zhou 2023 SI T2)", sulfur=1),
    Species("FFT", "2-furfurylthiol", 5, 0, "product", True,
            "odour threshold 0.006 ug/L in water", sulfur=1),
    Species("MFTD", "bis(2-methyl-3-furyl) disulfide (the MFT DIMER)", 10, 0,
            "product", True,
            "NOT AROMA LOSS. Threshold 0.00032 ug/L, i.e. 15.6x MORE POTENT "
            "than its own monomer, so the ~7-10% of MFT-equivalents that sit in "
            "it carry an OAV that MATCHES the monomer's (Zhou SI T2 prints "
            "3.21e5 against MFT's 3.18e5 at pH 7). Carried as a species with "
            "its own potency for exactly this reason.", sulfur=2),
    Species("FFTD", "bis(2-furfuryl) disulfide", 10, 0, "product", True, sulfur=2),
    Species("MMFT", "the MFT + methanethiol radical-coupling product", 6, 0,
            "product", True,
            "Zhang 2024's second measured MFT sink at 115 C, a channel the "
            "30 C data explicitly exclude.", sulfur=2),
    Species("MP3P", "2-mercapto-3-pentanone (the NORFURANEOL-diagnostic isomer)",
            5, 0, "product", True,
            "Cerny 2003 T3: 96% unlabelled from the NF spike, i.e. the sharpest "
            "single-species NF-route marker in the corpus. Cerny 2007 T4: "
            "94->95% XYLOSE-derived.", sulfur=1),
    Species("MP2P", "3-mercapto-2-pentanone (the THIAMINE-diagnostic isomer)",
            5, 0, "product", True,
            "Cerny 2007 T4: 77-90% THIAMINE-derived -- the opposite assignment "
            "to its own isomer, in the same pot. The pair is an isomer-split "
            "diagnostic that no lumped 'mercaptopentanone' node can express.",
            sulfur=1),
    Species("ACTZ", "2-acetylthiazole", 5, 1, "product", True, sulfur=1),
    # ---- B2.1: the Kang 2026 fed intermediate ------------------------------
    Species("TTCA", "2-(tetrahydroxybutyl)thiazolidine-4-carboxylic acid "
                    "(the cysteine + xylose condensate Kang 2026 charges)",
            8, 1, "reactant", True,
            "B2.1, NEW. Kang 2026's whole temperature ladder is run on PURIFIED "
            "TTCA at 10 mmol/L, not on a sugar + amino acid mixture, so the "
            "system cannot be represented by any pot the module already had. "
            "Two measured facts fix its topology and both are FIT rows: free "
            "cysteine is a TRANSIENT INTERMEDIATE of its degradation (Fig. S3 "
            "rises then falls at all three temperatures), and the free-cysteine "
            "yield is CAPPED AT 16.3 mol% of the cysteine moiety charged, so "
            ">=84% of the sulfur leaves without ever passing through free "
            "cysteine. Those two facts are why TTCA has exactly two fates here "
            "(r_ttca_cys and r_ttca_deg) rather than one.", sulfur=1),
    # ---- terminal pools ---------------------------------------------------
    Species("BND", "matrix-bound MFT conjugate (REVERSIBLE reservoir)",
            5, 0, "pool", False,
            "The product of covalent addition of MFT to a matrix electrophile. "
            "B2.1 SPLIT THIS SPECIES IN TWO. B2 carried one lumped C5 adduct for "
            "both thiols -- MFT and FFT are both C5H6OS, so the atom balance "
            "permitted it -- and the consequence, which B2 itself recorded as a "
            "limitation, is that a pot containing both thiols slowly converted "
            "FFT into MFT through the shared reservoir. BND (MFT) and BND_F "
            "(FFT) are now separate, the release step returns the thiol that was "
            "bound, and that limitation is retired. "
            "NOT TERMINAL: Stack 2018 measures the thiol-quinone conjugation as "
            "an EQUILIBRIUM, which is why added cysteine RELEASES bound FFT "
            "(Sun 2019). It is a SEQUESTRATION RESERVOIR, and treating it as a "
            "sink would over-predict permanent aroma loss on long timescales.",
            sulfur=1),
    Species("BND_F", "matrix-bound FFT conjugate (REVERSIBLE reservoir)",
            5, 0, "pool", False,
            "B2.1, NEW -- the FFT half of the split described on BND.", sulfur=1),
    Species("PRB", "thiol bound to a protein disulfide (1:1 / 2:1 exchange adduct)",
            5, 0, "pool", False,
            "B2.1, NEW. anantharamkrishnan2020b Fig. 7c: 2-furfurylthiol reacts "
            "with beta-lactoglobulin's disulfide linkages to give BOTH 1:1 "
            "(+114 Da) and 2:1 (+228 Da) adducts within 24 h at ambient "
            "temperature, 'in close analogy to the reactions with n-PrSH'. The "
            "sulfur branch had no protein sink at all. The channel is "
            "STOICHIOMETRIC in protein disulfides, not catalytic -- its capacity "
            "is the protein's disulfide inventory (2 per BLG = 1.09 mmol/L in "
            "that paper's 10% solution) -- which is why the partner is a titrated "
            "SITE POOL and not a catalyst.", sulfur=1),
    Species("OLG", "C-5 thiol oligomer", 5, 0, "pool", False,
            "van Seeventer 2001's acid-catalysed electrophilic oligomerisation "
            "at C-5 (85% H-D exchange at C-5 against 10% at C-4; air ~ argon). "
            "TERMINAL. Its RATE has no value on any FIT row -- see "
            "parameters_sulfur.NO_MEASURED_RATE.", sulfur=1),
    Species("MELE", "matrix electrophile pool (LUMPED, >=2 measured channels)",
            0, 0, "site", False,
            "ZERO atoms: an electrophile equivalent, not a molecule, so that the "
            "pool can be titrated in the units its only measurement uses -- "
            "8-10 mmol per g dry coffee solids (Charles-Bernard 2005, "
            "hydroxylamine titration), the only published site density. "
            "IT IS A LUMP OVER AT LEAST TWO MEASURED, CHEMICALLY DISTINCT "
            "CHANNELS, and the label says so rather than implying one "
            "mechanism: (i) melanoidin-bound pyrazinium (CROSSPY) electrophiles, "
            "Hofmann 2002; and (ii) the hydroxyhydroquinone-derived o-QUINONE, "
            "a DISCRETE SMALL MOLECULE which Muller & Hofmann 2007 identify as "
            "the DOMINANT thiol-trapping electrophile in real brew. A single "
            "lumped pool cannot separate them and no result here may be read as "
            "evidence for either. "
            "WHY A POOL AND NOT A RATE: the corpus's ~9e-4 1/s thiol-loss "
            "constant is PSEUDO-first-order -- it silently contains this "
            "concentration, so it is a property of one coffee matrix and not of "
            "the thiol. What the 30 C data constrain is the PRODUCT k2*[E]. "
            "Carrying [E] explicitly is what makes the sink DEPLETABLE, which "
            "is the whole content of the Hofmann-2002 80 C brew hold-out."),
    Species("OX", "oxidant equivalents", 0, 0, "site", False,
            "ZERO atoms. Zhang 2024 Fig. 1: at near-matched molar sulfur "
            "(123.8 vs 124.8 mM S) the OXIDISED additive (cystine) sends 54.2% "
            "of the MFT pool to the dimer and the REDUCED one (cysteine) only "
            "8.6%. The branch responds to REDOX STATE, not to concentration, "
            "so the oxidant is a state variable."),
    Species("PROT_SS", "protein disulfide sites (matrix input, titrated)", 0, 0,
            "site", False,
            "B2.1, NEW. ZERO atoms: a disulfide-linkage equivalent, in the units "
            "its only measurement uses -- anantharamkrishnan2020b counts 2 "
            "disulfides per beta-lactoglobulin, i.e. 1.09 mmol/L of sites in "
            "that paper's 10% (w/v) BLG solution. IT IS A MATRIX INPUT AND IT IS "
            "ZERO IN EVERY MODEL SYSTEM IN THE FIT AND HOLD-OUT PANELS, which is "
            "the whole point: the channel is STRUCTURALLY PRESENT and carries "
            "EXACTLY ZERO RATE in a protein-free pot, by mass action rather than "
            "by a flag. Kang's TTCA ladder, Hofmann's buffers, Zhou's water and "
            "Cerny's model solutions all contain no protein, so nothing in "
            "either panel is changed by this channel's existence."),
    Species("FRAG_N", "unassigned fragment nitrogen", 0, 1, "pool", False),
    Species("FRAG_S", "unassigned fragment sulfur", 0, 0, "pool", False, sulfur=1),
    Species("ACID", "titratable organic-acid equivalents from the osone sink",
            1, 0, "pool", False,
            "B2.2, NEW, AND IT EXISTS ONLY TO CARRY CHARGE. The deoxyosone "
            "sink is a LUMP over everything the corpus never identified. "
            "Martins 2005 measures that PART of the hexose deoxyosone flux "
            "terminates as formic acid (step 5) and acetic acid (step 8) while "
            "another part terminates as browning polymer (step 9), so the "
            "pentose analogue's acid yield is a FRACTION -- and that fraction "
            "is the single calibrated constant of the pH-trajectory model "
            "(ph_state.PhDrift.acid_yield), fitted on Amendment 7's three Zhou "
            "endpoints and on nothing else. "
            "CARBON CONVENTION, stated because it is a convention: the pool is "
            "counted in ACID EQUIVALENTS on a FORMIC basis, so it carries ONE "
            "carbon and the extra carbon of any acetic share stays in FRAG_C. "
            "Carbon still balances exactly, step by step; what the pool is FOR "
            "is the charge balance, not the carbon budget. "
            "It is TERMINAL: nothing in the sulfur network consumes it, so its "
            "existence cannot change any volatile prediction except through "
            "the pH.", ),
    # ---- B2.3: the two CARRIED-CENTRE pools -------------------------------
    Species("CBX", "carried carboxylate equivalents (a carboxyl group that "
                   "outlived the molecule that brought it)",
            1, 0, "pool", False,
            "B2.3, NEW, AND IT IS A CONSERVATION LAW RATHER THAN A CHEMISTRY "
            "CLAIM. B2.2's diagnosis sec. 3 measured the defect this pool "
            "exists to close: a sink step that consumes cysteine, the Amadori "
            "compound or TTCA DELETES that molecule's alpha-carboxylate, and "
            "since no reaction makes or destroys the sodium that titrated it, "
            "the pot manufactures strong base out of bookkeeping. Kang's "
            "120 C pot went to a predicted pH 11.4 against a measured 4.9 for "
            "exactly this reason. "
            "WHY IT IS NOT `ACID`. `ACID` is the LUMPED deoxyosone sink, whose "
            "acid yield is UNKNOWN and is the pH model's single calibrated "
            "constant -- it enters the charge balance multiplied by that "
            "fitted fraction. A carboxyl carried out of a molecule that "
            "demonstrably had one is not a fraction of anything: it is one "
            "equivalent, and it enters at full strength. Putting the two in "
            "one pool would have let a fitted yield scale a stoichiometric "
            "certainty. "
            "CARBON CONVENTION, identical to `ACID`'s: counted on a FORMIC "
            "basis, so one carbon per equivalent, and any further carbon of "
            "the leaving residue stays in FRAG_C. "
            "DECLARED APPROXIMATION: its pKa is `ph_state.ORGANIC_ACID_MIX`'s "
            "4.25, while the real leaving groups are heterogeneous (pyruvic "
            "acid 2.49 from the cysteine thermolysis lane, CO2 / carbonic acid "
            "6.35 from the two decarboxylations). The module carries no CO2 "
            "partition model -- no bundle in this corpus records a headspace "
            "volume -- so a carbonate pool would need a guessed Henry "
            "constant at 100-145 C. The mixture is declared instead, and the "
            "direction of the error is stated in the B2.3 report. "
            "TERMINAL: nothing consumes it."),
)

#: The concatenated table. B1's entries first, in B1's order, so trunk indices
#: are preserved exactly.
SULFUR_STATE: Tuple[Species, ...] = SPECIES + SULFUR_SPECIES

SULFUR_STATE_KEYS: Tuple[str, ...] = tuple(s.key for s in SULFUR_STATE)
SULFUR_INDEX: Mapping[str, int] = {s.key: i for i, s in enumerate(SULFUR_STATE)}
SULFUR_BY_KEY: Mapping[str, Species] = {s.key: s for s in SULFUR_STATE}
N_SULFUR_STATE = len(SULFUR_STATE)

#: The zero-atom site pools. They balance trivially, so the balance checker
#: cannot police them; this tuple is what the unit test policing them reads.
SITE_POOLS: Tuple[str, ...] = tuple(s.key for s in SULFUR_SPECIES if s.role == "site")

#: Terminal species: nothing may consume them.
#:
#: BND IS DELIBERATELY NOT IN THIS TUPLE. It was, until Stack 2018's measured
#: thiol-quinone equilibrium (K ~ 1e2-1e3 M^-1) established that the
#: conjugation is REVERSIBLE -- a sequestration equilibrium rather than a sink,
#: which is why added cysteine RELEASES bound thiol (Sun 2019). Treating the
#: bound adduct as terminal would over-predict permanent aroma loss on long
#: timescales, so the release step exists and BND is a reversible reservoir.
#:
#: PRB IS TERMINAL, and that is a decision the source forces rather than a
#: convenience. anantharamkrishnan2020b sec. 5d: no reversibility experiment is
#: reported for ANY adduct in that paper -- no dilution, no pH change, no
#: heating, no time series -- and the authors' own claim of irreversibility is
#: an assumption. The dossier's instruction is that an irreversible hexanal
#: sink is NOT supported; for the thiol-disulfide exchange it says the reverse
#: ('reversible in principle in the presence of other thiols') is equally
#: untested. With no measurement in either direction the conservative encoding
#: is the one that cannot invent a release rate, so PRB is terminal and the
#: absence of a release step is recorded here as a KNOWN GAP.
TERMINAL_POOLS: Tuple[str, ...] = (
    "OLG", "PRB", "FRAG_N", "FRAG_S", "ACID", "CBX")


# ---------------------------------------------------------------------------
# Molecular weights -- arithmetic, not parameters
# ---------------------------------------------------------------------------
# Used ONLY to convert a printed ug/L anchor into the module's mmol/L. Every
# value is the compound's formula weight; none is fitted and none is a rate.
MOLECULAR_WEIGHT_G_PER_MOL: Mapping[str, float] = {
    "PENT": 150.13,   # C5H10O5, ribose = xylose
    "ARP": 221.21,    # C8H15NO6, 1-deoxy-xylulosyl-alanine
    "Cys": 121.16,    # C3H7NO2S
    "THI": 337.27,    # thiamine hydrochloride, as Zhang 2024 weighs it
    "H2S": 34.08,
    "DPO": 130.10,    # C5H8O4
    "TDP": 130.10,
    "DDP": 114.10,    # C5H6O3
    "NF": 114.10,     # C5H6O3
    "PTR": 114.10,
    "FUR": 96.08,     # C5H4O2
    "HA": 60.05,      # C2H4O2
    "MP": 90.14,      # C3H6OS
    "HMP": 134.20,    # C5H10O2S
    "MESH": 48.11,    # CH4S
    "MFT": 114.16,    # C5H6OS
    "FFT": 114.16,    # C5H6OS
    "MFTD": 226.32,   # C10H10O2S2
    "FFTD": 226.32,
    "MMFT": 160.26,   # C6H8OS2, the MFT + MeSH coupling product
    "MP3P": 118.20,   # C5H10OS
    "MP2P": 118.20,
    "ACTZ": 127.16,   # C5H5NOS
    # B2.1
    "TTCA": 253.27,   # C8H15NO6S, L-cysteine + D-xylose - H2O
}


def ug_per_litre_to_mmol_per_litre(key: str, ug_per_litre: float) -> float:
    """Convert a printed ug/L (= ppb in water) anchor to mmol/L."""
    return float(ug_per_litre) / MOLECULAR_WEIGHT_G_PER_MOL[key] * 1.0e-3


def mmol_per_litre_to_ug_per_litre(key: str, mmol_per_litre: float) -> float:
    """The inverse, for reporting a prediction in the units it is printed in."""
    return float(mmol_per_litre) * MOLECULAR_WEIGHT_G_PER_MOL[key] * 1.0e3


# ---------------------------------------------------------------------------
# Element vectors and invariants over the EXTENDED state
# ---------------------------------------------------------------------------


def element_vector(element: str) -> Tuple[int, ...]:
    return tuple(getattr(s, element) for s in SULFUR_STATE)


def total_element(state, element: str) -> float:
    return float(
        sum(n * float(state[i]) for i, n in enumerate(element_vector(element)))
    )


def total_sulfur_extended(state) -> float:
    """Total sulfur, mmol S/L, over the extended state including every sink."""
    return total_element(state, "sulfur")


def initial_sulfur_state(concentrations: Mapping[str, float]):
    """Build an extended state vector from a {species_key: mmol/L} mapping."""
    import numpy as np

    y0 = np.zeros(N_SULFUR_STATE, dtype=float)
    for key, value in concentrations.items():
        if key not in SULFUR_INDEX:
            raise KeyError(
                f"unknown species {key!r}; expected one of {SULFUR_STATE_KEYS}"
            )
        if float(value) < 0.0:
            raise ValueError(f"negative initial concentration for {key!r}")
        y0[SULFUR_INDEX[key]] = float(value)
    return y0


def sulfur_state_as_dict(state) -> Dict[str, float]:
    return {key: float(state[SULFUR_INDEX[key]]) for key in SULFUR_STATE_KEYS}


# ---------------------------------------------------------------------------
# ODOUR POTENCY -- and the one place it changes a conclusion
# ---------------------------------------------------------------------------
# Aqueous odour thresholds, ug/L, from Zhou 2023 SI Table S2. PROVENANCE IS
# UNKNOWN BY THE SOURCE'S OWN ADMISSION: the SI gives no reference column and no
# footnote for any of them. They are ingested `basis_declared, provenance
# unknown` exactly as the K3 inventory sec. A.7.1 requires, and they are MODEL
# INPUTS, never scored predictions (sec. A.7 of the declaration: scoring a
# threshold would be a category error).
#
# THE ONE THAT MATTERS: the MFT DIMER is 15.6x MORE POTENT than the monomer
# (0.00032 against 0.005). Only 6.5-9.6% of MFT-equivalents sit in the dimer,
# but 0.096 / 0.064 > 1, so the dimer's OAV MATCHES the monomer's. An objective
# that scores dimerisation as a pure aroma loss is wrong by roughly the
# threshold ratio (K3 inventory sec. A.7.3). This module therefore tracks the
# dimer as a SPECIES and reports OAV per species, never as "free thiol".
ODOUR_THRESHOLD_UG_PER_L: Mapping[str, float] = {
    "MFTD": 0.00032,
    "MFT": 0.005,
    "FFT": 0.006,
    "ACTZ": 10.0,
    "FUR": 3000.0,
}

#: Thresholds the corpus does NOT have, for species this module carries. Named
#: so that a missing OAV is visibly a gap rather than a silent zero.
NO_THRESHOLD_AVAILABLE: Tuple[str, ...] = (
    "FFTD", "MMFT", "MP3P", "MP2P", "MESH", "MP", "NF", "H2S",
)


def odour_activity_values(state) -> Dict[str, object]:
    """
    OAV per species, plus the dimer-vs-monomer comparison that qualifies the
    whole thiol-consumption module.

    Returns floats for the five species with a threshold and the string
    ``'no_threshold_available'`` for the eight without. There is no default
    threshold and no imputation.
    """
    out: Dict[str, object] = {}
    for key, threshold in ODOUR_THRESHOLD_UG_PER_L.items():
        ug = mmol_per_litre_to_ug_per_litre(key, state[SULFUR_INDEX[key]])
        out[key] = ug / threshold
    for key in NO_THRESHOLD_AVAILABLE:
        out[key] = "no_threshold_available"
    mft = out.get("MFT", 0.0)
    dimer = out.get("MFTD", 0.0)
    out["dimer_over_monomer_OAV"] = (
        float(dimer) / float(mft) if isinstance(mft, float) and mft > 0 else float("nan")
    )
    out["potency_ratio_dimer_over_monomer"] = (
        ODOUR_THRESHOLD_UG_PER_L["MFT"] / ODOUR_THRESHOLD_UG_PER_L["MFTD"]
    )
    out["threshold_provenance"] = (
        "Zhou 2023 SI Table S2. basis_declared=true, provenance=unknown (the SI "
        "prints no citation for any threshold). Model INPUT, never a scored "
        "prediction."
    )
    return out
