#!/usr/bin/env python
# encoding: utf-8

name = "seed"
shortDesc = ""
longDesc = """

"""
autoGenerated=True
entry(
    index = 0,
    label = "cysteine + ribose <=> OCC(C(C(C(SCC(C(=O)O)N)O)O)O)O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+06,'cm^3/(mol*s)'), n=1, Ea=(50.208,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(600,'K'), comment="""Exact match found for rate rule [Carbonyl;Thiol]
    Euclidian distance = 0
    family: Thiol_Addition"""),
    longDesc = 
"""
Exact match found for rate rule [Carbonyl;Thiol]
Euclidian distance = 0
family: Thiol_Addition
""",
)

entry(
    index = 1,
    label = "cysteine + cysteine <=> SCC(C(SCC(C(=O)O)N)(O)O)N",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+06,'cm^3/(mol*s)'), n=1, Ea=(50.208,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(600,'K'), comment="""Exact match found for rate rule [Carbonyl;Thiol]
    Euclidian distance = 0
    family: Thiol_Addition"""),
    longDesc = 
"""
Exact match found for rate rule [Carbonyl;Thiol]
Euclidian distance = 0
family: Thiol_Addition
""",
)

entry(
    index = 2,
    label = "cysteine + OCC(C(C(C(SCC(C(=O)O)N)O)O)O)O <=> OCC(C(C(C(SCC(C(SCC(C(=O)O)N)(O)O)N)O)O)O)O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+06,'cm^3/(mol*s)'), n=1, Ea=(50.208,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(600,'K'), comment="""Exact match found for rate rule [Carbonyl;Thiol]
    Euclidian distance = 0
    family: Thiol_Addition"""),
    longDesc = 
"""
Exact match found for rate rule [Carbonyl;Thiol]
Euclidian distance = 0
family: Thiol_Addition
""",
)

entry(
    index = 3,
    label = "ribose + SCC(C(SCC(C(=O)O)N)(O)O)N <=> OCC(C(C(C(SCC(C(SCC(C(=O)O)N)(O)O)N)O)O)O)O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+06,'cm^3/(mol*s)'), n=1, Ea=(50.208,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(600,'K'), comment="""Exact match found for rate rule [Carbonyl;Thiol]
    Euclidian distance = 0
    family: Thiol_Addition"""),
    longDesc = 
"""
Exact match found for rate rule [Carbonyl;Thiol]
Euclidian distance = 0
family: Thiol_Addition
""",
)

entry(
    index = 4,
    label = "OCC(C(C(C(C(C(=O)O)(CS)N)O)O)O)O <=> cysteine + ribose",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(100000,'s^-1'), n=1, Ea=(117.152,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(600,'K'), comment="""Exact match found for rate rule [Aldol_Adduct]
    Euclidian distance = 0
    family: Retro_Aldol_Fragmentation"""),
    longDesc = 
"""
Exact match found for rate rule [Aldol_Adduct]
Euclidian distance = 0
family: Retro_Aldol_Fragmentation
""",
)

entry(
    index = 5,
    label = "OCC(C(C(C(SCC(C(C(C(C(CO)O)O)O)O)(C(=O)O)N)O)O)O)O <=> ribose + OCC(C(C(C(SCC(C(=O)O)N)O)O)O)O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(100000,'s^-1'), n=1, Ea=(117.152,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(600,'K'), comment="""Exact match found for rate rule [Aldol_Adduct]
    Euclidian distance = 0
    family: Retro_Aldol_Fragmentation"""),
    longDesc = 
"""
Exact match found for rate rule [Aldol_Adduct]
Euclidian distance = 0
family: Retro_Aldol_Fragmentation
""",
)

entry(
    index = 6,
    label = "ribose + OCC(C(C(C(C(C(=O)O)(CS)N)O)O)O)O <=> OCC(C(C(C(SCC(C(C(C(C(CO)O)O)O)O)(C(=O)O)N)O)O)O)O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+06,'cm^3/(mol*s)'), n=1, Ea=(50.208,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(600,'K'), comment="""Exact match found for rate rule [Carbonyl;Thiol]
    Euclidian distance = 0
    family: Thiol_Addition"""),
    longDesc = 
"""
Exact match found for rate rule [Carbonyl;Thiol]
Euclidian distance = 0
family: Thiol_Addition
""",
)

entry(
    index = 7,
    label = "OCC(C(C(C(C(C(=O)O)(CSC(C(CS)N)(O)O)N)O)O)O)O <=> ribose + SCC(C(SCC(C(=O)O)N)(O)O)N",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(100000,'s^-1'), n=1, Ea=(117.152,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(600,'K'), comment="""Exact match found for rate rule [Aldol_Adduct]
    Euclidian distance = 0
    family: Retro_Aldol_Fragmentation"""),
    longDesc = 
"""
Exact match found for rate rule [Aldol_Adduct]
Euclidian distance = 0
family: Retro_Aldol_Fragmentation
""",
)

entry(
    index = 8,
    label = "cysteine + OCC(C(C(C(C(C(=O)O)(CS)N)O)O)O)O <=> OCC(C(C(C(C(C(=O)O)(CSC(C(CS)N)(O)O)N)O)O)O)O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+06,'cm^3/(mol*s)'), n=1, Ea=(50.208,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(600,'K'), comment="""Exact match found for rate rule [Carbonyl;Thiol]
    Euclidian distance = 0
    family: Thiol_Addition"""),
    longDesc = 
"""
Exact match found for rate rule [Carbonyl;Thiol]
Euclidian distance = 0
family: Thiol_Addition
""",
)

entry(
    index = 9,
    label = "cysteine + OCC(C(C(C(C(C(=O)O)(CS)N)O)O)O)O <=> OCC(C(C(C(C(C(SCC(C(=O)O)N)(O)O)(CS)N)O)O)O)O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+06,'cm^3/(mol*s)'), n=1, Ea=(53.4587,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(600,'K'), comment="""Exact match found for rate rule [Carbonyl;Thiol]
    Euclidian distance = 0
    family: Thiol_Addition
    Ea raised from 50.3 to 53.5 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Exact match found for rate rule [Carbonyl;Thiol]
Euclidian distance = 0
family: Thiol_Addition
Ea raised from 50.3 to 53.5 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 10,
    label = "OCC(C(C(C(C(C(=O)O)(CS)N)O)O)O)O + OCC(C(C(C(C(C(=O)O)(CS)N)O)O)O)O <=> OCC(C(C(C(C(C(=O)O)(CSC(C(C(C(C(C(CO)O)O)O)O)(CS)N)(O)O)N)O)O)O)O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+06,'cm^3/(mol*s)'), n=1, Ea=(53.4587,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(600,'K'), comment="""Exact match found for rate rule [Carbonyl;Thiol]
    Euclidian distance = 0
    family: Thiol_Addition
    Ea raised from 50.3 to 53.5 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Exact match found for rate rule [Carbonyl;Thiol]
Euclidian distance = 0
family: Thiol_Addition
Ea raised from 50.3 to 53.5 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 11,
    label = "OCC(C(C(C(C(C(=O)O)(CSC(C(C(C(C(C(CO)O)O)O)O)(CS)N)(O)O)N)O)O)O)O <=> ribose + OCC(C(C(C(C(C(SCC(C(=O)O)N)(O)O)(CS)N)O)O)O)O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(100000,'s^-1'), n=1, Ea=(117.152,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(600,'K'), comment="""Exact match found for rate rule [Aldol_Adduct]
    Euclidian distance = 0
    family: Retro_Aldol_Fragmentation"""),
    longDesc = 
"""
Exact match found for rate rule [Aldol_Adduct]
Euclidian distance = 0
family: Retro_Aldol_Fragmentation
""",
)

entry(
    index = 12,
    label = "OCC(C(C(C(SCC(C(SCC(C(C(C(C(CO)O)O)O)O)(C(=O)O)N)(O)O)N)O)O)O)O <=> ribose + OCC(C(C(C(SCC(C(SCC(C(=O)O)N)(O)O)N)O)O)O)O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(100000,'s^-1'), n=1, Ea=(117.152,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(600,'K'), comment="""Exact match found for rate rule [Aldol_Adduct]
    Euclidian distance = 0
    family: Retro_Aldol_Fragmentation"""),
    longDesc = 
"""
Exact match found for rate rule [Aldol_Adduct]
Euclidian distance = 0
family: Retro_Aldol_Fragmentation
""",
)

entry(
    index = 13,
    label = "OCC(C(C(C(C(C(=O)O)(CS)N)O)O)O)O + OCC(C(C(C(SCC(C(=O)O)N)O)O)O)O <=> OCC(C(C(C(SCC(C(SCC(C(C(C(C(CO)O)O)O)O)(C(=O)O)N)(O)O)N)O)O)O)O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+06,'cm^3/(mol*s)'), n=1, Ea=(50.208,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(600,'K'), comment="""Exact match found for rate rule [Carbonyl;Thiol]
    Euclidian distance = 0
    family: Thiol_Addition"""),
    longDesc = 
"""
Exact match found for rate rule [Carbonyl;Thiol]
Euclidian distance = 0
family: Thiol_Addition
""",
)

entry(
    index = 14,
    label = "ribose + OCC(C(C(C(C(C(=O)O)(CSC(C(CS)N)(O)O)N)O)O)O)O <=> OCC(C(C(C(SCC(C(SCC(C(C(C(C(CO)O)O)O)O)(C(=O)O)N)(O)O)N)O)O)O)O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+06,'cm^3/(mol*s)'), n=1, Ea=(50.208,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(600,'K'), comment="""Exact match found for rate rule [Carbonyl;Thiol]
    Euclidian distance = 0
    family: Thiol_Addition"""),
    longDesc = 
"""
Exact match found for rate rule [Carbonyl;Thiol]
Euclidian distance = 0
family: Thiol_Addition
""",
)

entry(
    index = 15,
    label = "cysteine + OCC(C(C(C(SCC(C(C(C(C(CO)O)O)O)O)(C(=O)O)N)O)O)O)O <=> OCC(C(C(C(SCC(C(SCC(C(=O)O)N)(O)O)(C(C(C(C(CO)O)O)O)O)N)O)O)O)O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+06,'cm^3/(mol*s)'), n=1, Ea=(53.4587,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(600,'K'), comment="""Exact match found for rate rule [Carbonyl;Thiol]
    Euclidian distance = 0
    family: Thiol_Addition
    Ea raised from 50.3 to 53.5 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Exact match found for rate rule [Carbonyl;Thiol]
Euclidian distance = 0
family: Thiol_Addition
Ea raised from 50.3 to 53.5 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 16,
    label = "ribose + OCC(C(C(C(C(C(SCC(C(=O)O)N)(O)O)(CS)N)O)O)O)O <=> OCC(C(C(C(SCC(C(SCC(C(=O)O)N)(O)O)(C(C(C(C(CO)O)O)O)O)N)O)O)O)O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+06,'cm^3/(mol*s)'), n=1, Ea=(50.208,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(600,'K'), comment="""Exact match found for rate rule [Carbonyl;Thiol]
    Euclidian distance = 0
    family: Thiol_Addition"""),
    longDesc = 
"""
Exact match found for rate rule [Carbonyl;Thiol]
Euclidian distance = 0
family: Thiol_Addition
""",
)

entry(
    index = 17,
    label = "OCC(C(C(C(C(C(=O)O)(CS)N)O)O)O)O + OCC(C(C(C(SCC(C(C(C(C(CO)O)O)O)O)(C(=O)O)N)O)O)O)O <=> OCC(C(C(C(SCC(C(C(C(C(CO)O)O)O)O)(C(SCC(C(C(C(C(CO)O)O)O)O)(C(=O)O)N)(O)O)N)O)O)O)O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+06,'cm^3/(mol*s)'), n=1, Ea=(53.4587,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(600,'K'), comment="""Exact match found for rate rule [Carbonyl;Thiol]
    Euclidian distance = 0
    family: Thiol_Addition
    Ea raised from 50.3 to 53.5 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Exact match found for rate rule [Carbonyl;Thiol]
Euclidian distance = 0
family: Thiol_Addition
Ea raised from 50.3 to 53.5 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 18,
    label = "ribose + OCC(C(C(C(C(C(=O)O)(CSC(C(C(C(C(C(CO)O)O)O)O)(CS)N)(O)O)N)O)O)O)O <=> OCC(C(C(C(SCC(C(C(C(C(CO)O)O)O)O)(C(SCC(C(C(C(C(CO)O)O)O)O)(C(=O)O)N)(O)O)N)O)O)O)O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+06,'cm^3/(mol*s)'), n=1, Ea=(50.208,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(600,'K'), comment="""Exact match found for rate rule [Carbonyl;Thiol]
    Euclidian distance = 0
    family: Thiol_Addition"""),
    longDesc = 
"""
Exact match found for rate rule [Carbonyl;Thiol]
Euclidian distance = 0
family: Thiol_Addition
""",
)

entry(
    index = 19,
    label = "OCC(C(C(C(SCC(C(C(C(C(CO)O)O)O)O)(C(SCC(C(C(C(C(CO)O)O)O)O)(C(=O)O)N)(O)O)N)O)O)O)O <=> ribose + OCC(C(C(C(SCC(C(SCC(C(=O)O)N)(O)O)(C(C(C(C(CO)O)O)O)O)N)O)O)O)O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(100000,'s^-1'), n=1, Ea=(117.152,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(600,'K'), comment="""Exact match found for rate rule [Aldol_Adduct]
    Euclidian distance = 0
    family: Retro_Aldol_Fragmentation"""),
    longDesc = 
"""
Exact match found for rate rule [Aldol_Adduct]
Euclidian distance = 0
family: Retro_Aldol_Fragmentation
""",
)

