"""Compound identity: resolve any repository spelling to one registry entry.

The registry is ``data/keys/compounds.yml`` (generated by
``scripts/generators/build_compound_registry.py``; do not hand-edit). Molecules are
keyed by InChIKey, everything else by ``id``; ``aliases`` holds every spelling that
occurs anywhere under ``data/``.

Until 2026-09-01 five modules each kept their own alias table and normaliser
(``benchmark_validation.BENCHMARK_NAME_ALIASES``, ``external_validation._COMPOUND_ALIASES``,
``experiment_value._alias_keys``, ``sensory.SensoryDatabase.alias_map``,
``matrix_calibration_registry._normalize_compound``), and the benchmark matcher fell
through to a ``difflib`` similarity at ratio 0.75. This module is the one place a
spelling becomes an identity. It is deliberately exact: no substring or similarity
matching. Unknown spellings resolve to ``None``; callers decide what that means.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from functools import lru_cache
from typing import Dict, FrozenSet, List, Mapping, Optional, Tuple

from src import data_access, data_paths
from src.text_utils import normalize_compound_name as norm


@dataclass(frozen=True)
class CompoundKey:
    id: str
    display_name: str
    kind: str  # molecule | compound_class | marker_class | process_lever
    inchikey: Optional[str] = None
    smiles: Optional[str] = None
    cas: Optional[str] = None
    compound_class: Optional[str] = None
    aliases: Tuple[str, ...] = ()
    members: Tuple[str, ...] = ()  # marker_class: member ids
    members_of_class: Optional[str] = None  # compound_class: the `class` value its members carry

    @property
    def norms(self) -> FrozenSet[str]:
        names = {self.display_name, self.id, *self.aliases}
        return frozenset(n for n in (norm(x) for x in names) if n)


@dataclass(frozen=True)
class _Registry:
    entries: Tuple[CompoundKey, ...]
    by_id: Mapping[str, CompoundKey]
    by_norm: Mapping[str, CompoundKey]
    by_inchikey: Mapping[str, CompoundKey]
    by_class: Mapping[str, Tuple[CompoundKey, ...]] = field(default_factory=dict)


@lru_cache(maxsize=1)
def _registry() -> _Registry:
    payload = data_access.load_yaml(data_paths.COMPOUND_REGISTRY) or {}
    entries: List[CompoundKey] = []
    for rec in payload.get("compounds", []):
        entries.append(
            CompoundKey(
                id=str(rec["id"]),
                display_name=str(rec["display_name"]),
                kind=str(rec["kind"]),
                inchikey=rec.get("inchikey"),
                smiles=rec.get("smiles"),
                cas=rec.get("cas"),
                compound_class=rec.get("class"),
                aliases=tuple(str(a) for a in rec.get("aliases", [])),
                members=tuple(str(m) for m in rec.get("members", [])),
                members_of_class=rec.get("members_of_class"),
            )
        )
    by_id = {e.id: e for e in entries}
    by_norm: Dict[str, CompoundKey] = {}
    for e in entries:
        for n in e.norms:
            other = by_norm.get(n)
            if other is not None and other.id != e.id:
                raise data_access.DataFileMalformed(
                    f"{data_paths.rel(data_paths.COMPOUND_REGISTRY)}: spelling {n!r} is claimed by "
                    f"both {other.id} and {e.id}"
                )
            by_norm[n] = e
    by_inchikey = {e.inchikey: e for e in entries if e.inchikey}
    by_class: Dict[str, List[CompoundKey]] = {}
    for e in entries:
        if e.compound_class:
            by_class.setdefault(e.compound_class, []).append(e)
    return _Registry(
        entries=tuple(entries),
        by_id=by_id,
        by_norm=by_norm,
        by_inchikey=by_inchikey,
        by_class={k: tuple(v) for k, v in by_class.items()},
    )


def all_compounds() -> Tuple[CompoundKey, ...]:
    return _registry().entries


def get(compound_id: str) -> CompoundKey:
    """Registry entry by ``id``; raises ``KeyError`` for an unknown id."""
    return _registry().by_id[compound_id]


def resolve(spelling: str) -> Optional[CompoundKey]:
    """Exact (normalised) resolution of any repository spelling; ``None`` if unknown."""
    if not spelling:
        return None
    return _registry().by_norm.get(norm(spelling))


def canonical_name(spelling: str) -> str:
    """Display name of the resolved entry, or the input unchanged when unknown."""
    key = resolve(spelling)
    return key.display_name if key else spelling


def same_compound(a: str, b: str) -> bool:
    """True when two spellings resolve to the same entry (exact identity only)."""
    ka, kb = resolve(a), resolve(b)
    return ka is not None and kb is not None and ka.id == kb.id


def members_of(key: CompoundKey) -> Tuple[CompoundKey, ...]:
    """Molecules a class/marker entry stands for; empty for a molecule."""
    reg = _registry()
    if key.kind == "compound_class" and key.members_of_class:
        return reg.by_class.get(key.members_of_class, ())
    if key.kind == "marker_class":
        return tuple(reg.by_id[m] for m in key.members if m in reg.by_id)
    return ()


def match_norms(spelling: str) -> FrozenSet[str]:
    """Every normalised spelling that counts as a match for ``spelling``.

    A molecule matches its own spellings. A class (``pyrazines``) or marker set
    (``CML/CEL``) matches its own spellings plus those of every member, which is what the
    retired ``BENCHMARK_NAME_ALIASES`` table encoded by hand for pyrazines.
    """
    key = resolve(spelling)
    if key is None:
        return frozenset({norm(spelling)}) if norm(spelling) else frozenset()
    norms = set(key.norms)
    for member in members_of(key):
        norms |= member.norms
    return frozenset(norms)


def benchmark_alias_table() -> Dict[str, FrozenSet[str]]:
    """``{normalised spelling: match set}`` for every spelling in the registry.

    Drop-in replacement for the hand-written ``BENCHMARK_NAME_ALIASES``: a superset of it
    (pinned by tests/unit/test_compound_keys.py), derived from data instead of typed.
    """
    table: Dict[str, FrozenSet[str]] = {}
    for entry in _registry().entries:
        norms = set(entry.norms)
        for member in members_of(entry):
            norms |= member.norms
        for n in entry.norms:
            table[n] = frozenset(norms)
    return table


def clear_cache() -> None:
    _registry.cache_clear()
