"""Paper identity: one ``paper_id`` per DOI, and which records cite it.

The registry is ``data/keys/papers.yml`` (generated by
``scripts/generators/build_paper_registry.py``; do not hand-edit). It is derived from
the DOI fields already present in the registries, benchmarks, payloads and timeseries
files, so it asserts which records share a paper -- not that a DOI is correct, which is
``scripts/ci/citation_gate.py``'s job.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from functools import lru_cache
from typing import Dict, Mapping, Optional, Tuple

from src import data_access, data_paths

# A DOI is "10.<registrant>/<suffix>"; the suffix may contain ()<>:; (Wiley). We stop at
# whitespace, quotes, a markdown table pipe or a closing bracket, then trim trailing
# punctuation and markdown emphasis.
_DOI_RE = re.compile(r"10\.\d{4,9}/[^\s\"'|\]]+", re.I)


def normalise_doi(raw: str) -> Optional[str]:
    """Extract and normalise the first DOI in ``raw``; ``None`` if there is none.

    Placeholder DOIs (an all-zero registrant, used by example/template files) are ignored.
    """
    m = _DOI_RE.search(str(raw or ""))
    if not m:
        return None
    doi = m.group(0).rstrip(".,;:*")
    while doi.endswith(")") and doi.count("(") < doi.count(")"):
        doi = doi[:-1].rstrip(".,;:*")
    doi = doi.lower()
    # Example/template files use an all-zero registrant; treat those as placeholders.
    registrant = doi[3:].split("/", 1)[0]
    if registrant and registrant.strip("0") == "":
        return None
    return doi


@dataclass(frozen=True)
class PaperKey:
    paper_id: str
    doi: str
    citation: Optional[str]
    dossier: Optional[str]
    intake_ids: Tuple[str, ...]
    record_ids: Mapping[str, Tuple[str, ...]]


@lru_cache(maxsize=1)
def _registry() -> Tuple[Dict[str, PaperKey], Dict[str, PaperKey]]:
    payload = data_access.load_yaml(data_paths.PAPER_REGISTRY) or {}
    by_id: Dict[str, PaperKey] = {}
    by_doi: Dict[str, PaperKey] = {}
    for rec in payload.get("papers", []):
        key = PaperKey(
            paper_id=str(rec["paper_id"]),
            doi=str(rec["doi"]),
            citation=rec.get("citation"),
            dossier=rec.get("dossier"),
            intake_ids=tuple(rec.get("intake_ids", [])),
            record_ids={f: tuple(ids) for f, ids in (rec.get("record_ids") or {}).items()},
        )
        if key.paper_id in by_id or key.doi in by_doi:
            raise data_access.DataFileMalformed(
                f"{data_paths.rel(data_paths.PAPER_REGISTRY)}: duplicate paper_id/doi {key.paper_id} / {key.doi}"
            )
        by_id[key.paper_id] = key
        by_doi[key.doi] = key
    return by_id, by_doi


def all_papers() -> Tuple[PaperKey, ...]:
    return tuple(_registry()[0].values())


def get(paper_id: str) -> PaperKey:
    return _registry()[0][paper_id]


def for_doi(raw_doi: str) -> Optional[PaperKey]:
    doi = normalise_doi(raw_doi)
    return _registry()[1].get(doi) if doi else None


def clear_cache() -> None:
    _registry.cache_clear()
