"""
tests/unit/test_kinetic_core_b1.py

Focused unit tests for `src/kinetic_core` (Build Wave B1: trunk network +
melanoidin mass sink). Deliberately narrow and fast: mass conservation,
non-negativity, Arrhenius round-trip, the registry's provenance and policy
guarantees, the hold-out firewall, and one pinned Martins-condition regression.
"""

from __future__ import annotations

import math
from pathlib import Path

import numpy as np
import pytest

from src.kinetic_core import (
    FITTED_KEYS,
    MARTINS_M4,
    MEASURED_LABEL_TO_KEY,
    REACTIONS,
    SCHIFF_AMADORI_SPLIT,
    T_REF_K,
    Reaction,
    assert_no_dft,
    check_ph_homogeneity,
    fitted_placeholders,
    integrate,
    operative_parameters,
    rate_constants_at,
    registry_metadata,
    total_carbon,
    total_nitrogen,
    validate_balance,
)
from src.kinetic_core.parameters import R_KJ

ROOT = Path(__file__).resolve().parents[2]

INITIAL = {"Glc": 200.0, "Gly": 200.0}

# The frozen variant-A fit, from results/validation/kinetic_core_b1_fit_report.json
# (generated by scripts/generators/generate_kinetic_core_b1_fit.py). Pinned here
# so the tests do not depend on a results artefact being present.
FITTED_A = {
    "k_glc_frag": (1.000032373292967e-08, 180.69531857985976),
    "k_mgo_mel": (0.02272608289635856, 20.043206355884948),
    "k_fa_frag": (3.4646810085648807e-08, 20.53065919356619),
    "k_aa_frag": (0.011812994692176768, 20.000000150449104),
}


@pytest.fixture(scope="module")
def parameters():
    return operative_parameters(FITTED_A)


# ---------------------------------------------------------------------------
# Stoichiometry and conservation
# ---------------------------------------------------------------------------


def test_every_reaction_balances_carbon_and_nitrogen():
    validate_balance()
    for reaction in REACTIONS:
        for element in ("carbon", "nitrogen"):
            left, right = reaction.atom_balance(element)
            assert left == right, f"{reaction.key}: {element} {left} -> {right}"


def test_unbalanced_reaction_is_refused():
    bad = Reaction("r_bad", {"TDG": 1}, {"FA": 1}, "k_tdg_fa")  # loses 5 carbon
    with pytest.raises(ValueError, match="carbon does not balance"):
        validate_balance([bad])


def test_melanoidin_sink_is_terminal():
    for reaction in REACTIONS:
        assert "MEL_C" not in reaction.reactants
        assert "MEL_N" not in reaction.reactants
        assert "FRAG_C" not in reaction.reactants


@pytest.mark.parametrize("temperature_c", [100.0, 140.0, 180.0, 200.0])
def test_total_carbon_is_conserved(parameters, temperature_c):
    grid = np.linspace(0.0, 60.0, 41)
    run = integrate(parameters, temperature_c + 273.15, INITIAL, grid)
    closure = run.carbon_closure()
    assert closure["initial_carbon_mmol_L"] == pytest.approx(1600.0)
    assert closure["max_relative_drift"] < 1e-9, closure


@pytest.mark.parametrize("temperature_c", [100.0, 200.0])
def test_total_nitrogen_is_conserved(parameters, temperature_c):
    grid = np.linspace(0.0, 60.0, 41)
    run = integrate(parameters, temperature_c + 273.15, INITIAL, grid)
    closure = run.nitrogen_closure()
    assert closure["initial_nitrogen_mmol_L"] == pytest.approx(200.0)
    assert closure["max_relative_drift"] < 1e-9, closure


def test_carbon_conservation_holds_over_hours_and_seconds(parameters):
    for duration in (1.0 / 60.0, 1.0, 360.0):
        grid = np.linspace(0.0, duration, 25)
        run = integrate(parameters, 393.15, INITIAL, grid)
        assert run.carbon_closure()["max_relative_drift"] < 1e-9


def test_conservation_catches_a_stoichiometry_typo(parameters):
    """The invariant must actually be able to fail, or it proves nothing."""
    from src.kinetic_core import network
    from src.kinetic_core.species import BY_KEY, INDEX, SPECIES_KEYS

    broken = np.array(network.STOICHIOMETRY, copy=True)
    # delete the C5 residue that r_tdg_fa routes into FRAG_C
    broken[INDEX["FRAG_C"], network.REACTION_KEYS.index("r_tdg_fa")] = 0.0

    state = np.zeros(len(SPECIES_KEYS))
    state[INDEX["Glc"]] = 200.0
    state[INDEX["Gly"]] = 200.0
    state[INDEX["AMA"]] = 5.0
    state[INDEX["TDG"]] = 1.0
    rates = network.reaction_rates(state, rate_constants_at(parameters, 373.15))

    carbon = np.array([BY_KEY[key].carbon for key in SPECIES_KEYS], dtype=float)
    intact_drift = float(carbon @ (network.STOICHIOMETRY @ rates))
    broken_drift = float(carbon @ (broken @ rates))
    assert abs(intact_drift) < 1e-9
    assert abs(broken_drift) > 1e-6, "a deleted product must break the carbon balance"


# ---------------------------------------------------------------------------
# Non-negativity
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("temperature_c", [100.0, 120.0, 160.0, 200.0])
def test_states_never_go_negative(parameters, temperature_c):
    grid = np.linspace(0.0, 120.0, 121)
    run = integrate(parameters, temperature_c + 273.15, INITIAL, grid)
    assert float(run.concentrations.min()) >= 0.0
    assert run.metadata["worst_raw_negative_before_clip"] > -1e-8


def test_non_negativity_survives_a_depleted_start(parameters):
    """Start with a trace of everything and integrate long past exhaustion."""
    start = {"Glc": 1e-6, "Gly": 1e-6, "AMA": 1e-6, "TDG": 1e-6, "ODG": 1e-6,
             "MGO": 1e-6, "FA": 1e-6, "AA": 1e-6}
    run = integrate(parameters, 473.15, start, np.linspace(0.0, 600.0, 61))
    assert float(run.concentrations.min()) >= 0.0


def test_melanoidin_pool_is_monotone_non_decreasing(parameters):
    run = integrate(parameters, 393.15, INITIAL, np.linspace(0.0, 120.0, 121))
    mel = run.melanoidin_mmol_L()
    assert np.all(np.diff(mel) >= -1e-12)


# ---------------------------------------------------------------------------
# Arrhenius
# ---------------------------------------------------------------------------


def test_arrhenius_round_trip_at_the_reference_temperature():
    for key, parameter in MARTINS_M4.items():
        assert parameter.k_at(T_REF_K) == pytest.approx(parameter.k_ref, rel=1e-12), key


def test_arrhenius_matches_the_closed_form():
    parameter = MARTINS_M4["k_tdg_mel"]
    for temperature_k in (353.15, 373.15, 393.15, 473.15):
        expected = parameter.k_ref * math.exp(
            -(parameter.ea_kj_mol / R_KJ) * (1.0 / temperature_k - 1.0 / T_REF_K)
        )
        assert parameter.k_at(temperature_k) == pytest.approx(expected, rel=1e-12)


def test_arrhenius_is_monotone_increasing_in_temperature():
    for key, parameter in MARTINS_M4.items():
        assert parameter.k_at(353.15) < parameter.k_at(373.15) < parameter.k_at(393.15), key


def test_amadori_rate_is_derived_not_parameterised(parameters):
    k = rate_constants_at(parameters, T_REF_K)
    expected = (
        SCHIFF_AMADORI_SPLIT["ratio_amadori_over_schiff_pseudo_first_order"]
        * k["r_schiff"]
        * SCHIFF_AMADORI_SPLIT["amine_loading_mmol_L_for_the_ratio"]
    )
    assert k["r_amadori"] == pytest.approx(expected, rel=1e-12)


def test_the_schiff_amadori_split_ratio_barely_moves_the_trunk(parameters, monkeypatch):
    """
    The source REFUSES the Schiff/Amadori split, so the pinned ratio must not be
    strongly load-bearing.

    MEASURED, not asserted, and NOT zero: at 100 C / 120 min a 10x increase in
    the ratio (44.9 -> 449) moves the Amadori pool by -1.1% and the melanoidin
    sink by +7.5%. The mechanism is that the Schiff pool holds up ~2.5 mmol/L
    of amine at the pinned ratio; releasing it faster feeds the BIMOLECULAR
    melanoidin step, which is the most ratio-sensitive quantity in the network.

    This test pins that sensitivity at under 10% for a 10x ratio change rather
    than claiming it away. The consequence is recorded in the hold-out report:
    the split cannot explain a 1.45x browning bias, but it is not free either.
    """
    grid = np.array([0.0, 60.0, 120.0])
    base = integrate(parameters, 373.15, INITIAL, grid)
    from src.kinetic_core import network as network_module

    monkeypatch.setitem(
        network_module.SCHIFF_AMADORI_SPLIT,
        "ratio_amadori_over_schiff_pseudo_first_order",
        449.0,
    )
    moved = integrate(parameters, 373.15, INITIAL, grid)
    for label, a, b in (
        ("AMA", base.series("AMA")[-1], moved.series("AMA")[-1]),
        ("melanoidin", base.melanoidin_mmol_L()[-1], moved.melanoidin_mmol_L()[-1]),
        ("Glc", base.series("Glc")[-1], moved.series("Glc")[-1]),
    ):
        assert abs(b - a) / a < 0.10, f"{label}: {a} -> {b}"


# ---------------------------------------------------------------------------
# Registry provenance and standing policy
# ---------------------------------------------------------------------------


def test_no_dft_derived_parameter_anywhere():
    assert_no_dft(MARTINS_M4)
    assert_no_dft(fitted_placeholders())
    assert registry_metadata(MARTINS_M4)["dft_free"] is True


def test_no_dft_module_is_imported_by_the_package():
    """The package must not reach any computational-barrier module."""
    banned = ("dft_refiner", "dft_coverage_map", "barrier_constants",
              "computational_gap", "diffusion_ts")
    for path in (ROOT / "src" / "kinetic_core").glob("*.py"):
        text = path.read_text(encoding="utf-8")
        for token in banned:
            assert f"import {token}" not in text, f"{path.name} imports {token}"
            assert f"from src.{token}" not in text, f"{path.name} imports {token}"


def test_every_parameter_carries_its_provenance():
    for key, parameter in MARTINS_M4.items():
        assert parameter.source_anchor and "Martins" in parameter.source_anchor, key
        assert parameter.dossier_anchor, key
        assert parameter.conditions, key
        assert parameter.ph_of_measurement is not None, key
        assert parameter.unit in ("1/min", "L/(mmol*min)"), key
        assert parameter.ea_kj_mol is not None and parameter.k_ref is not None, key
        assert parameter.rate_transfer in (
            "licensed", "not_licensed", "licensed_at_measurement_ph_only"
        ), key


def test_network_is_ph_homogeneous_and_has_no_ph_or_aw_term():
    assert check_ph_homogeneity(MARTINS_M4) == pytest.approx(6.8)
    metadata = registry_metadata(MARTINS_M4)
    assert metadata["ph_term_present"] is False
    assert metadata["aw_term_present"] is False
    assert metadata["network_ph"] == pytest.approx(6.8)
    assert "sign-crossings" in metadata["ph_term_absent_because"]


def test_mixed_ph_registry_is_refused():
    from dataclasses import replace

    mixed = dict(MARTINS_M4)
    mixed["k_tdg_mel"] = replace(mixed["k_tdg_mel"], ph_of_measurement=5.0)
    with pytest.raises(ValueError, match="NO family-level pH term can pass"):
        check_ph_homogeneity(mixed)


def test_unpopulated_fitted_parameters_refuse_to_integrate():
    parameters = dict(MARTINS_M4)
    parameters.update(fitted_placeholders())
    with pytest.raises(ValueError, match="unpopulated"):
        rate_constants_at(parameters, T_REF_K)


def test_fitted_steps_are_labelled_as_fitted():
    for key, parameter in fitted_placeholders().items():
        assert key in FITTED_KEYS
        assert parameter.evidence_class == "derived_from_fit_data"
        assert "fitted_here" in parameter.flags
        assert "no_literature_value" in parameter.flags
        assert parameter.rate_transfer == "not_licensed"


def test_extrapolation_beyond_the_measured_window_is_flagged(parameters):
    run = integrate(parameters, 473.15, INITIAL, [0.0, 1.0])
    warnings = run.metadata["extrapolation_warnings"]
    assert warnings, "200 C is outside every parameter's 80-120 C window"
    assert all("measured over 80-120 C" in line for line in warnings)

    inside = integrate(parameters, 373.15, INITIAL, [0.0, 1.0])
    assert inside.metadata["extrapolation_warnings"] == []


# ---------------------------------------------------------------------------
# The hold-out firewall
# ---------------------------------------------------------------------------


def test_the_browning_holdout_is_not_reachable_from_the_runtime_package():
    """
    epsilon = 0.64 L/(mmol*cm) and 282 L/(mol*cm) are the Module 4 hold-outs.
    Neither may appear anywhere in src/kinetic_core, and the measured-label map
    must not expose the melanoidin response to the fit objective.
    """
    assert "melanoidins" not in MEASURED_LABEL_TO_KEY
    assert "MEL_C" not in MEASURED_LABEL_TO_KEY.values()
    assert "MEL_N" not in MEASURED_LABEL_TO_KEY.values()

    import importlib

    held_out = (0.64, 640.0, 282.0, 0.282)

    def numbers_in(value, depth=0):
        if depth > 6:
            return
        if isinstance(value, bool):
            return
        if isinstance(value, (int, float)):
            yield float(value)
        elif isinstance(value, dict):
            for item in value.values():
                yield from numbers_in(item, depth + 1)
        elif isinstance(value, (list, tuple, set)):
            for item in value:
                yield from numbers_in(item, depth + 1)
        elif hasattr(value, "__dataclass_fields__") and not isinstance(value, type):
            for field in value.__dataclass_fields__:
                yield from numbers_in(getattr(value, field), depth + 1)

    for name in ("species", "parameters", "network", "integrate"):
        module = importlib.import_module(f"src.kinetic_core.{name}")
        for attribute, value in vars(module).items():
            if attribute.startswith("__"):
                continue
            for number in numbers_in(value):
                assert not any(
                    math.isclose(number, target, rel_tol=1e-12) for target in held_out
                ), f"src/kinetic_core/{name}.py exposes the held-out value {number}"


def test_the_fit_script_allow_list_excludes_the_holdout():
    """The fit stage must name the hold-out only to exclude it."""
    import importlib

    module = importlib.import_module(
        "scripts.generators.generate_kinetic_core_b1_fit"
    )
    assert "melanoidins" in module.HOLDOUT_SPECIES
    assert "melanoidins" not in module.FIT_SPECIES
    assert not set(module.FIT_SPECIES) & set(module.HOLDOUT_SPECIES)
    assert set(module.FIT_SPECIES) <= set(MEASURED_LABEL_TO_KEY)


# ---------------------------------------------------------------------------
# Pinned regression at the Martins condition
# ---------------------------------------------------------------------------


def test_martins_condition_regression(parameters):
    """
    100 C, glucose 200 mmol/L + glycine 200 mmol/L, 120 min, variant-A
    parameters. Pinned from the wave-B1 fit report; a change here means a
    change in the network or in a measured constant, and must be explained.
    """
    run = integrate(parameters, 373.15, INITIAL, [0.0, 120.0])
    end = {key: float(run.series(key)[-1])
           for key in ("Glc", "Fru", "Gly", "AMA", "TDG", "ODG", "MGO", "FA", "AA")}
    expected = {
        "Glc": 126.32, "Fru": 18.04, "Gly": 175.38, "AMA": 11.74,
        "TDG": 0.747, "ODG": 0.1274, "MGO": 3.416, "FA": 2.504, "AA": 11.25,
    }
    for key, value in expected.items():
        assert end[key] == pytest.approx(value, rel=2e-3), f"{key}: {end[key]}"

    assert float(run.melanoidin_mmol_L()[-1]) == pytest.approx(10.34, rel=2e-3)
    assert float(run.melanoidin_c_over_n()[-1]) == pytest.approx(9.51, rel=2e-3)


def test_melanoidin_c_over_n_starts_at_the_step_9_stoichiometry(parameters):
    """
    The first melanoidin formed is pure step-9 product, C8N1. Carbon-only
    additions (the fitted methylglyoxal channel) then raise the ratio, which is
    the direction Brands' elemental series measures.
    """
    run = integrate(parameters, 373.15, INITIAL, [0.0, 0.5, 60.0, 120.0])
    cn = run.melanoidin_c_over_n()
    # C/N can never fall below the step-9 repeat unit, and the carbon-only
    # channel is already contributing within the first half-minute.
    assert 8.0 <= cn[1] < 8.5, cn[1]
    assert cn[1] < cn[2] < cn[-1]


def test_every_intermediate_has_a_formation_and_a_consumption_term():
    """The defect this rebuild exists to fix: nothing may only accumulate."""
    produced, consumed = set(), set()
    for reaction in REACTIONS:
        produced.update(reaction.products)
        consumed.update(reaction.reactants)
    for key in ("Fru", "SB", "AMA", "TDG", "ODG", "MGO", "FA", "AA"):
        assert key in produced, f"{key} is never formed"
        assert key in consumed, f"{key} is never consumed"
    # the terminal pools are the declared exception
    for key in ("MEL_C", "MEL_N", "FRAG_C"):
        assert key in produced and key not in consumed


def test_integrator_rejects_a_non_stiff_method(parameters):
    with pytest.raises(ValueError, match="stiff-capable"):
        integrate(parameters, 373.15, INITIAL, [0.0, 1.0], method="RK45")


def test_bdf_and_lsoda_agree(parameters):
    grid = np.array([0.0, 30.0, 60.0])
    lsoda = integrate(parameters, 393.15, INITIAL, grid, method="LSODA")
    bdf = integrate(parameters, 393.15, INITIAL, grid, method="BDF")
    assert bdf.series("AMA")[-1] == pytest.approx(lsoda.series("AMA")[-1], rel=1e-4)
    assert bdf.melanoidin_mmol_L()[-1] == pytest.approx(
        lsoda.melanoidin_mmol_L()[-1], rel=1e-4
    )


def test_state_helpers_agree_with_the_run(parameters):
    run = integrate(parameters, 373.15, INITIAL, [0.0, 60.0])
    row = run.concentrations[-1]
    assert total_carbon(row) == pytest.approx(1600.0, rel=1e-9)
    assert total_nitrogen(row) == pytest.approx(200.0, rel=1e-9)
